function HCRank_mobs(level)
    if level <= 20 then
        return {
            ["Defias Bodyguard"] = {["Rank"] = 1,["Kills"] = 774},
            ["Defias Highwayman"] = {["Rank"] = 2,["Kills"] = 636},
            ["Defias Trapper"] = {["Rank"] = 3,["Kills"] = 575},
            ["Rockjaw Bonesnapper"] = {["Rank"] = 4,["Kills"] = 391},
            ["Vagash"] = {["Rank"] = 5,["Kills"] = 257},
            ["Defias Pillager"] = {["Rank"] = 6,["Kills"] = 244},
            ["Rotting Ancestor"] = {["Rank"] = 7,["Kills"] = 242},
            ["Sunscale Scytheclaw"] = {["Rank"] = 8,["Kills"] = 235},
            ["Tunnel Rat Geomancer"] = {["Rank"] = 9,["Kills"] = 231},
            ["Defias Looter"] = {["Rank"] = 10,["Kills"] = 222},
            ["Riverpaw Outrunner"] = {["Rank"] = 11,["Kills"] = 219},
            ["Voidwalker"] = {["Rank"] = 12,["Kills"] = 219},
            ["Lunaclaw"] = {["Rank"] = 13,["Kills"] = 218},
            ["Benny Blaanco"] = {["Rank"] = 14,["Kills"] = 211},
            ["Burning Blade Apprentice"] = {["Rank"] = 15,["Kills"] = 209},
            ["Burning Blade Toxicologist"] = {["Rank"] = 16,["Kills"] = 203},
            ["Riverpaw Bandit"] = {["Rank"] = 17,["Kills"] = 200},
            ["Son of Arugal"] = {["Rank"] = 18,["Kills"] = 195},
            ["Warlord Krom'zar"] = {["Rank"] = 19,["Kills"] = 190},
            ["Carver Molsen"] = {["Rank"] = 20,["Kills"] = 186},
            ["Tunnel Rat Kobold"] = {["Rank"] = 21,["Kills"] = 177},
            ["Razormane Defender"] = {["Rank"] = 22,["Kills"] = 176},
            ["Stormscale Wave Rider"] = {["Rank"] = 23,["Kills"] = 170},
            ["Dreadmaw Crocolisk"] = {["Rank"] = 24,["Kills"] = 162},
            ["Fizzle Darkstorm"] = {["Rank"] = 25,["Kills"] = 162},
            ["Stonesplinter Trogg"] = {["Rank"] = 26,["Kills"] = 159},
            ["Harvest Watcher"] = {["Rank"] = 27,["Kills"] = 157},
            ["Defias Smuggler"] = {["Rank"] = 28,["Kills"] = 154},
            ["Longsnout"] = {["Rank"] = 29,["Kills"] = 152},
            ["Stonesplinter Skullthumper"] = {["Rank"] = 30,["Kills"] = 149},
            ["Witchwing Slayer"] = {["Rank"] = 31,["Kills"] = 146},
            ["Venture Co. Enforcer"] = {["Rank"] = 32,["Kills"] = 141},
            ["Murloc Tidehunter"] = {["Rank"] = 33,["Kills"] = 141},
            ["Bristleback Trapper"] = {["Rank"] = 34,["Kills"] = 138},
            ["Tunnel Rat Forager"] = {["Rank"] = 35,["Kills"] = 138},
            ["Stonesplinter Seer"] = {["Rank"] = 36,["Kills"] = 126},
            ["Blackrock Outrunner"] = {["Rank"] = 37,["Kills"] = 126},
            ["Tunnel Rat Digger"] = {["Rank"] = 38,["Kills"] = 125},
            ["Murloc Coastrunner"] = {["Rank"] = 39,["Kills"] = 118},
            ["Gnarlpine Defender"] = {["Rank"] = 40,["Kills"] = 114},
            ["Ol' Sooty"] = {["Rank"] = 41,["Kills"] = 113},
            ["Riverpaw Brute"] = {["Rank"] = 42,["Kills"] = 113},
            ["Kolkar Invader"] = {["Rank"] = 43,["Kills"] = 110},
            ["Hecklefang Hyena"] = {["Rank"] = 44,["Kills"] = 105},
            ["Gnarlpine Shaman"] = {["Rank"] = 45,["Kills"] = 104},
            ["Defias Pathstalker"] = {["Rank"] = 46,["Kills"] = 103},
            ["Raging Moonkin"] = {["Rank"] = 47,["Kills"] = 101},
            ["Venture Co. Overseer"] = {["Rank"] = 48,["Kills"] = 101},
            ["Dire Condor"] = {["Rank"] = 49,["Kills"] = 101},
            ["Deepmoss Matriarch"] = {["Rank"] = 50,["Kills"] = 101},
            ["Lillith Nefara"] = {["Rank"] = 51,["Kills"] = 100},
            ["Razormane Water Seeker"] = {["Rank"] = 52,["Kills"] = 99},
            ["Theramore Marine"] = {["Rank"] = 53,["Kills"] = 98},
            ["Defias Knuckleduster"] = {["Rank"] = 54,["Kills"] = 97},
            ["Kodo Matriarch"] = {["Rank"] = 55,["Kills"] = 94},
            ["Imp Minion"] = {["Rank"] = 56,["Kills"] = 93},
            ["Sand Shark"] = {["Rank"] = 57,["Kills"] = 93},
            ["Ragefire Trogg"] = {["Rank"] = 58,["Kills"] = 93},
            ["Defias Bandit"] = {["Rank"] = 59,["Kills"] = 92},
            ["Murloc Netter"] = {["Rank"] = 60,["Kills"] = 92},
            ["Gazz'uz"] = {["Rank"] = 61,["Kills"] = 81},
            ["Carnivous the Breaker"] = {["Rank"] = 62,["Kills"] = 81},
            ["Taskmaster Fizzule"] = {["Rank"] = 63,["Kills"] = 81},
            ["Oggleflint"] = {["Rank"] = 64,["Kills"] = 80},
            ["Stormscale Siren"] = {["Rank"] = 65,["Kills"] = 80},
            ["Gnarlpine Augur"] = {["Rank"] = 66,["Kills"] = 79},
            ["Burning Blade Fanatic"] = {["Rank"] = 67,["Kills"] = 79},
            ["Expedition Commando"] = {["Rank"] = 68,["Kills"] = 78},
            ["Stonesplinter Bonesnapper"] = {["Rank"] = 69,["Kills"] = 76},
            ["Polly"] = {["Rank"] = 70,["Kills"] = 76},
            ["Rockjaw Skullthumper"] = {["Rank"] = 71,["Kills"] = 75},
            ["Stonesplinter Scout"] = {["Rank"] = 72,["Kills"] = 75},
            ["Greymist Coastrunner"] = {["Rank"] = 73,["Kills"] = 75},
            ["Foreman Grills"] = {["Rank"] = 74,["Kills"] = 74},
            ["Kolkar Packhound"] = {["Rank"] = 75,["Kills"] = 73},
            ["Southsea Cannoneer"] = {["Rank"] = 76,["Kills"] = 73},
            ["Chok'sul"] = {["Rank"] = 77,["Kills"] = 73},
            ["Minion of Sethir"] = {["Rank"] = 78,["Kills"] = 72},
            ["Defias Dockmaster"] = {["Rank"] = 79,["Kills"] = 71},
            ["Stonesplinter Shaman"] = {["Rank"] = 80,["Kills"] = 70},
            ["Old Icebeard"] = {["Rank"] = 81,["Kills"] = 69},
            ["Prowler"] = {["Rank"] = 82,["Kills"] = 69},
            ["Moonrage Darksoul"] = {["Rank"] = 83,["Kills"] = 68},
            ["Verog the Dervish"] = {["Rank"] = 84,["Kills"] = 64},
            ["Moonstalker Runt"] = {["Rank"] = 85,["Kills"] = 63},
            ["Hogger"] = {["Rank"] = 86,["Kills"] = 62},
            ["Rift Spawn"] = {["Rank"] = 87,["Kills"] = 62},
            ["Witchwing Roguefeather"] = {["Rank"] = 88,["Kills"] = 62},
            ["Dalaran Serpent"] = {["Rank"] = 89,["Kills"] = 62},
            ["Gradok"] = {["Rank"] = 90,["Kills"] = 62},
            ["Wandering Spirit"] = {["Rank"] = 91,["Kills"] = 61},
            ["Haren Swifthoof"] = {["Rank"] = 92,["Kills"] = 61},
            ["Foe Reaper 4000"] = {["Rank"] = 93,["Kills"] = 61},
            ["Venture Co. Drudger"] = {["Rank"] = 94,["Kills"] = 61},
            ["Bristleback Hunter"] = {["Rank"] = 95,["Kills"] = 61},
            ["Coyote"] = {["Rank"] = 96,["Kills"] = 60},
            ["Ravenclaw Servant"] = {["Rank"] = 97,["Kills"] = 60},
            ["Bristleback Thornweaver"] = {["Rank"] = 98,["Kills"] = 60},
            ["Lightning Hide"] = {["Rank"] = 99,["Kills"] = 59},
            ["Compact Harvest Reaper"] = {["Rank"] = 100,["Kills"] = 59},
        }
    elseif level <= 30 then
        return {
            ["Deepmoss Matriarch"] = {["Rank"] = 1,["Kills"] = 181},
            ["Stitches"] = {["Rank"] = 2,["Kills"] = 134},
            ["Compact Harvest Reaper"] = {["Rank"] = 3,["Kills"] = 114},
            ["Razormane Stalker"] = {["Rank"] = 4,["Kills"] = 80},
            ["Mor'Ladim"] = {["Rank"] = 5,["Kills"] = 70},
            ["Silithid Swarm"] = {["Rank"] = 6,["Kills"] = 62},
            ["Carver Molsen"] = {["Rank"] = 7,["Kills"] = 61},
            ["Blackrock Sentry"] = {["Rank"] = 8,["Kills"] = 53},
            ["Blackrock Champion"] = {["Rank"] = 9,["Kills"] = 50},
            ["Shadowhide Slayer"] = {["Rank"] = 10,["Kills"] = 50},
            ["Dark Strand Assassin"] = {["Rank"] = 11,["Kills"] = 50},
            ["Defias Blackguard"] = {["Rank"] = 12,["Kills"] = 46},
            ["Dragonmaw Raider"] = {["Rank"] = 13,["Kills"] = 44},
            ["Unseen"] = {["Rank"] = 14,["Kills"] = 42},
            ["Chok'sul"] = {["Rank"] = 15,["Kills"] = 42},
            ["Wretched Bodyguard"] = {["Rank"] = 16,["Kills"] = 40},
            ["Hillsbrad Miner"] = {["Rank"] = 17,["Kills"] = 40},
            ["Blackrock Outrunner"] = {["Rank"] = 18,["Kills"] = 38},
            ["Defias Raider"] = {["Rank"] = 19,["Kills"] = 37},
            ["Goggeroc"] = {["Rank"] = 20,["Kills"] = 37},
            ["Warlord Krom'zar"] = {["Rank"] = 21,["Kills"] = 36},
            ["Bael'dun Officer"] = {["Rank"] = 22,["Kills"] = 34},
            ["Deepmoss Creeper"] = {["Rank"] = 23,["Kills"] = 33},
            ["Devouring Ectoplasm"] = {["Rank"] = 24,["Kills"] = 33},
            ["Galak Assassin"] = {["Rank"] = 25,["Kills"] = 33},
            ["Wildthorn Lurker"] = {["Rank"] = 26,["Kills"] = 32},
            ["Defias Pirate"] = {["Rank"] = 27,["Kills"] = 31},
            ["Defias Highwayman"] = {["Rank"] = 28,["Kills"] = 31},
            ["Grunt"] = {["Rank"] = 29,["Kills"] = 31},
            ["Bloodfury Ripper"] = {["Rank"] = 30,["Kills"] = 31},
            ["Bael'dun Foreman"] = {["Rank"] = 31,["Kills"] = 30},
            ["Defias Digger"] = {["Rank"] = 32,["Kills"] = 30},
            ["Edwin VanCleef"] = {["Rank"] = 33,["Kills"] = 30},
            ["Dun Garok Soldier"] = {["Rank"] = 34,["Kills"] = 30},
            ["Bloodfury Ambusher"] = {["Rank"] = 35,["Kills"] = 29},
            ["Deviate Creeper"] = {["Rank"] = 36,["Kills"] = 28},
            ["Flesh Eating Worm"] = {["Rank"] = 37,["Kills"] = 28},
            ["Aku'mai Snapjaw"] = {["Rank"] = 38,["Kills"] = 28},
            ["Redridge Basher"] = {["Rank"] = 39,["Kills"] = 27},
            ["Blackrock Summoner"] = {["Rank"] = 40,["Kills"] = 27},
            ["Black Widow Hatchling"] = {["Rank"] = 41,["Kills"] = 27},
            ["Cursed Sailor"] = {["Rank"] = 42,["Kills"] = 27},
            ["Defias Rioter"] = {["Rank"] = 43,["Kills"] = 27},
            ["Silithid Grub"] = {["Rank"] = 44,["Kills"] = 26},
            ["Shadowhide Brute"] = {["Rank"] = 45,["Kills"] = 26},
            ["Hannah Bladeleaf"] = {["Rank"] = 46,["Kills"] = 26},
            ["Nightbane Dark Runner"] = {["Rank"] = 47,["Kills"] = 26},
            ["Horde Guard"] = {["Rank"] = 48,["Kills"] = 25},
            ["Besseleth"] = {["Rank"] = 49,["Kills"] = 25},
            ["Dragonmaw Grunt"] = {["Rank"] = 50,["Kills"] = 25},
            ["Defias Overseer"] = {["Rank"] = 51,["Kills"] = 24},
            ["Skeletal Miner"] = {["Rank"] = 52,["Kills"] = 24},
            ["Bael'dun Excavator"] = {["Rank"] = 53,["Kills"] = 24},
            ["Taskmaster Whipfang"] = {["Rank"] = 54,["Kills"] = 23},
            ["Blackrock Tracker"] = {["Rank"] = 55,["Kills"] = 23},
            ["Eliza's Guard"] = {["Rank"] = 56,["Kills"] = 23},
            ["Bleak Worg"] = {["Rank"] = 57,["Kills"] = 23},
            ["Druid of the Fang"] = {["Rank"] = 58,["Kills"] = 22},
            ["Silithid Swarmer"] = {["Rank"] = 59,["Kills"] = 22},
            ["Befouled Water Elemental"] = {["Rank"] = 60,["Kills"] = 22},
            ["Cursed Marine"] = {["Rank"] = 61,["Kills"] = 22},
            ["Lupine Delusion"] = {["Rank"] = 62,["Kills"] = 22},
            ["Crimson Ooze"] = {["Rank"] = 63,["Kills"] = 21},
            ["Riverpaw Bandit"] = {["Rank"] = 64,["Kills"] = 21},
            ["Defias Night Blade"] = {["Rank"] = 65,["Kills"] = 21},
            ["Redridge Alpha"] = {["Rank"] = 66,["Kills"] = 21},
            ["Syndicate Watchman"] = {["Rank"] = 67,["Kills"] = 21},
            ["Marcus Bel"] = {["Rank"] = 68,["Kills"] = 20},
            ["Mosshide Mongrel"] = {["Rank"] = 69,["Kills"] = 20},
            ["Ol' Sooty"] = {["Rank"] = 70,["Kills"] = 20},
            ["Defias Squallshaper"] = {["Rank"] = 71,["Kills"] = 20},
            ["Skeletal Horror"] = {["Rank"] = 72,["Kills"] = 20},
            ["Defias Inmate"] = {["Rank"] = 73,["Kills"] = 20},
            ["Nightbane Shadow Weaver"] = {["Rank"] = 74,["Kills"] = 20},
            ["Pesterhide Snarler"] = {["Rank"] = 75,["Kills"] = 20},
            ["Venture Co. Enforcer"] = {["Rank"] = 76,["Kills"] = 19},
            ["Taskmaster Fizzule"] = {["Rank"] = 77,["Kills"] = 19},
            ["Deepmoss Hatchling"] = {["Rank"] = 78,["Kills"] = 19},
            ["Wandering Protector"] = {["Rank"] = 79,["Kills"] = 19},
            ["Shadowhide Warrior"] = {["Rank"] = 80,["Kills"] = 19},
            ["Blackrock Gladiator"] = {["Rank"] = 81,["Kills"] = 19},
            ["Windshear Digger"] = {["Rank"] = 82,["Kills"] = 19},
            ["Deviate Dreadfang"] = {["Rank"] = 83,["Kills"] = 18},
            ["Defias Henchman"] = {["Rank"] = 84,["Kills"] = 18},
            ["Lupine Horror"] = {["Rank"] = 85,["Kills"] = 18},
            ["Redridge Mystic"] = {["Rank"] = 86,["Kills"] = 17},
            ["Bone Chewer"] = {["Rank"] = 87,["Kills"] = 17},
            ["Blackrock Shadowcaster"] = {["Rank"] = 88,["Kills"] = 16},
            ["Blackrock Hunter"] = {["Rank"] = 89,["Kills"] = 16},
            ["Thora Feathermoon"] = {["Rank"] = 90,["Kills"] = 16},
            ["Hillsbrad Foreman"] = {["Rank"] = 91,["Kills"] = 16},
            ["Necromancer Reginald"] = {["Rank"] = 92,["Kills"] = 15},
            ["Remnants Footman"] = {["Rank"] = 93,["Kills"] = 15},
            ["Barrens Guard"] = {["Rank"] = 94,["Kills"] = 15},
            ["Silithid Protector"] = {["Rank"] = 95,["Kills"] = 15},
            ["Hillsbrad Peasant"] = {["Rank"] = 96,["Kills"] = 15},
            ["Slavering Worg"] = {["Rank"] = 97,["Kills"] = 15},
            ["Greymist Coastrunner"] = {["Rank"] = 98,["Kills"] = 14},
            ["Defias Worker"] = {["Rank"] = 99,["Kills"] = 14},
            ["Syndicate Shadow Mage"] = {["Rank"] = 100,["Kills"] = 14},
        }
    elseif level <= 40 then
        return {
            ["Blastmaster Emi Shortfuse"] = {["Rank"] = 1,["Kills"] = 43},
            ["Undead Ravager"] = {["Rank"] = 2,["Kills"] = 29},
            ["Unseen"] = {["Rank"] = 3,["Kills"] = 28},
            ["Kurzen Commando"] = {["Rank"] = 4,["Kills"] = 26},
            ["Magrami Spectre"] = {["Rank"] = 5,["Kills"] = 26},
            ["Warleader Kintoza"] = {["Rank"] = 6,["Kills"] = 25},
            ["Slim's Friend"] = {["Rank"] = 7,["Kills"] = 19},
            ["Witherbark Headhunter"] = {["Rank"] = 8,["Kills"] = 18},
            ["Deranged Ancient"] = {["Rank"] = 9,["Kills"] = 18},
            ["Dragonmaw Raider"] = {["Rank"] = 10,["Kills"] = 17},
            ["Tarren Mill Deathguard"] = {["Rank"] = 11,["Kills"] = 17},
            ["Grenka Bloodscreech"] = {["Rank"] = 12,["Kills"] = 15},
            ["Syndicate Prowler"] = {["Rank"] = 13,["Kills"] = 14},
            ["Burning Blade Felsworn"] = {["Rank"] = 14,["Kills"] = 13},
            ["Syndicate Thief"] = {["Rank"] = 15,["Kills"] = 12},
            ["Darkmist Silkspinner"] = {["Rank"] = 16,["Kills"] = 12},
            ["Nightbane Dark Runner"] = {["Rank"] = 17,["Kills"] = 11},
            ["Eliza's Guard"] = {["Rank"] = 18,["Kills"] = 11},
            ["Scarlet Monk"] = {["Rank"] = 19,["Kills"] = 11},
            ["Elder Saltwater Crocolisk"] = {["Rank"] = 20,["Kills"] = 11},
            ["Crushridge Mauler"] = {["Rank"] = 21,["Kills"] = 11},
            ["Bloodscalp Scout"] = {["Rank"] = 22,["Kills"] = 11},
            ["Maraudine Bonepaw"] = {["Rank"] = 23,["Kills"] = 11},
            ["Barrens Guard"] = {["Rank"] = 24,["Kills"] = 10},
            ["Hillsbrad Miner"] = {["Rank"] = 25,["Kills"] = 10},
            ["Kolkar Destroyer"] = {["Rank"] = 26,["Kills"] = 10},
            ["Mosh'Ogg Warmonger"] = {["Rank"] = 27,["Kills"] = 10},
            ["Scarlet Myrmidon"] = {["Rank"] = 28,["Kills"] = 10},
            ["Scorpid Reaver"] = {["Rank"] = 29,["Kills"] = 9},
            ["Dun Garok Soldier"] = {["Rank"] = 30,["Kills"] = 9},
            ["Stromgarde Cavalryman"] = {["Rank"] = 31,["Kills"] = 9},
            ["Dun Garok Mountaineer"] = {["Rank"] = 32,["Kills"] = 9},
            ["Saltscale Oracle"] = {["Rank"] = 33,["Kills"] = 9},
            ["Saltscale Warrior"] = {["Rank"] = 34,["Kills"] = 9},
            ["Scarlet Torturer"] = {["Rank"] = 35,["Kills"] = 8},
            ["Screeching Harpy"] = {["Rank"] = 36,["Kills"] = 8},
            ["Southshore Guard"] = {["Rank"] = 37,["Kills"] = 8},
            ["Morbent Fel"] = {["Rank"] = 38,["Kills"] = 8},
            ["Mor'Ladim"] = {["Rank"] = 39,["Kills"] = 8},
            ["Bloodscalp Mystic"] = {["Rank"] = 40,["Kills"] = 8},
            ["Hammerfall Peon"] = {["Rank"] = 41,["Kills"] = 8},
            ["Dalaran Shield Guard"] = {["Rank"] = 42,["Kills"] = 7},
            ['Tapoke "Slim" Jahn'] = {["Rank"] = 43,["Kills"] = 7},
            ["Aku'mai Snapjaw"] = {["Rank"] = 44,["Kills"] = 7},
            ["Stitches"] = {["Rank"] = 45,["Kills"] = 7},
            ["Chieftain Nek'rosh"] = {["Rank"] = 46,["Kills"] = 7},
            ["Salt Flats Scavenger"] = {["Rank"] = 47,["Kills"] = 7},
            ["Scarlet Sentry"] = {["Rank"] = 48,["Kills"] = 7},
            ["Syndicate Spy"] = {["Rank"] = 49,["Kills"] = 7},
            ["Scarlet Gallant"] = {["Rank"] = 50,["Kills"] = 7},
            ["Drywallow Vicejaw"] = {["Rank"] = 51,["Kills"] = 7},
            ["Bhag'thera"] = {["Rank"] = 52,["Kills"] = 7},
            ["Dark Iron Tunneler"] = {["Rank"] = 53,["Kills"] = 6},
            ["Old Town Thug"] = {["Rank"] = 54,["Kills"] = 6},
            ["Vile Sting"] = {["Rank"] = 55,["Kills"] = 6},
            ["Captain Ironhill"] = {["Rank"] = 56,["Kills"] = 6},
            ["Syndicate Wizard"] = {["Rank"] = 57,["Kills"] = 6},
            ["Bloodscalp Shaman"] = {["Rank"] = 58,["Kills"] = 6},
            ["Dark Iron Agent"] = {["Rank"] = 59,["Kills"] = 6},
            ["Bloodscalp Hunter"] = {["Rank"] = 60,["Kills"] = 6},
            ["Witherbark Rogue"] = {["Rank"] = 61,["Kills"] = 6},
            ["Witherbark Raider"] = {["Rank"] = 62,["Kills"] = 6},
            ["Bloodsail Mage"] = {["Rank"] = 63,["Kills"] = 6},
            ["Felguard"] = {["Rank"] = 64,["Kills"] = 5},
            ["Magus Palon"] = {["Rank"] = 65,["Kills"] = 5},
            ["Highland Thrasher"] = {["Rank"] = 66,["Kills"] = 5},
            ["Skeletal Raider"] = {["Rank"] = 67,["Kills"] = 5},
            ["Kurzen War Tiger"] = {["Rank"] = 68,["Kills"] = 5},
            ["Quilguard Champion"] = {["Rank"] = 69,["Kills"] = 5},
            ["Mechanized Guardian"] = {["Rank"] = 70,["Kills"] = 5},
            ["Coral Shark"] = {["Rank"] = 71,["Kills"] = 5},
            ["Kurzen Jungle Fighter"] = {["Rank"] = 72,["Kills"] = 5},
            ["Crushridge Warmonger"] = {["Rank"] = 73,["Kills"] = 5},
            ["Nancy Vishas"] = {["Rank"] = 74,["Kills"] = 5},
            ["Drywallow Daggermaw"] = {["Rank"] = 75,["Kills"] = 5},
            ["Witherbark Darkcaller"] = {["Rank"] = 76,["Kills"] = 5},
            ["Colonel Kurzen"] = {["Rank"] = 77,["Kills"] = 5},
            ["Kurzen Subchief"] = {["Rank"] = 78,["Kills"] = 5},
            ["Stonard Grunt"] = {["Rank"] = 79,["Kills"] = 5},
            ["Balgaras the Foul"] = {["Rank"] = 80,["Kills"] = 4},
            ["Young Stranglethorn Tiger"] = {["Rank"] = 81,["Kills"] = 4},
            ["Galak Assassin"] = {["Rank"] = 82,["Kills"] = 4},
            ["Dalaran Theurgist"] = {["Rank"] = 83,["Kills"] = 4},
            ["Skeleton"] = {["Rank"] = 84,["Kills"] = 4},
            ["Harlus Ashbuckle"] = {["Rank"] = 85,["Kills"] = 4},
            ["Dark Iron Demolitionist"] = {["Rank"] = 86,["Kills"] = 4},
            ["Torn Fin Tidehunter"] = {["Rank"] = 87,["Kills"] = 4},
            ["Forsaken Infiltrator"] = {["Rank"] = 88,["Kills"] = 4},
            ["Enraged Wyvern"] = {["Rank"] = 89,["Kills"] = 4},
            ["Razorfen Servitor"] = {["Rank"] = 90,["Kills"] = 4},
            ["Freewind Brave"] = {["Rank"] = 91,["Kills"] = 4},
            ["Eliza"] = {["Rank"] = 92,["Kills"] = 4},
            ["Pesterhide Snarler"] = {["Rank"] = 93,["Kills"] = 4},
            ["Saltstone Crystalhide"] = {["Rank"] = 94,["Kills"] = 4},
            ["Holdout Medic"] = {["Rank"] = 95,["Kills"] = 4},
            ["Kovork"] = {["Rank"] = 96,["Kills"] = 4},
            ["Witherbark Shadow Hunter"] = {["Rank"] = 97,["Kills"] = 4},
            ["Accursed Slitherblade"] = {["Rank"] = 98,["Kills"] = 4},
            ["Drywhisker Digger"] = {["Rank"] = 99,["Kills"] = 4},
            ["Maraudine Wrangler"] = {["Rank"] = 100,["Kills"] = 4},
        }
    elseif level <= 59 then
        return {
            ["Fleet Master Firallon"] = {["Rank"] = 1,["Kills"] = 16},
            ["Firemane Ash Tail"] = {["Rank"] = 2,["Kills"] = 13},
            ["Khan Hratha"] = {["Rank"] = 3,["Kills"] = 10},
            ["Maraudine Bonepaw"] = {["Rank"] = 4,["Kills"] = 10},
            ["Grol the Destroyer"] = {["Rank"] = 5,["Kills"] = 10},
            ["Firemane Scout"] = {["Rank"] = 6,["Kills"] = 9},
            ["Magrami Spectre"] = {["Rank"] = 7,["Kills"] = 9},
            ["Vilebranch Kidnapper"] = {["Rank"] = 8,["Kills"] = 8},
            ["King Mosh"] = {["Rank"] = 9,["Kills"] = 8},
            ["Fallen Hero"] = {["Rank"] = 10,["Kills"] = 8},
            ["Bloodsail Sea Dog"] = {["Rank"] = 11,["Kills"] = 7},
            ["Wastewander Assassin"] = {["Rank"] = 12,["Kills"] = 7},
            ["Gorishi Hive Guard"] = {["Rank"] = 13,["Kills"] = 7},
            ["Jaedenar Adept"] = {["Rank"] = 14,["Kills"] = 7},
            ["Maraudine Wrangler"] = {["Rank"] = 15,["Kills"] = 6},
            ["Somnus"] = {["Rank"] = 16,["Kills"] = 6},
            ["King Bangalash"] = {["Rank"] = 17,["Kills"] = 6},
            ["Zetharia"] = {["Rank"] = 18,["Kills"] = 6},
            ["Drywallow Daggermaw"] = {["Rank"] = 19,["Kills"] = 5},
            ["Baelfyr"] = {["Rank"] = 20,["Kills"] = 5},
            ["Bloodsail Elder Magus"] = {["Rank"] = 21,["Kills"] = 5},
            ["Hatecrest Serpent Guard"] = {["Rank"] = 22,["Kills"] = 5},
            ["Zul'Farrak Zombie"] = {["Rank"] = 23,["Kills"] = 5},
            ["Bloodsail Warlock"] = {["Rank"] = 24,["Kills"] = 4},
            ["Undead Ravager"] = {["Rank"] = 25,["Kills"] = 4},
            ["Enraged Silverback Gorilla"] = {["Rank"] = 26,["Kills"] = 4},
            ["Scalebane Captain"] = {["Rank"] = 27,["Kills"] = 4},
            ["Mosh'Ogg Warmonger"] = {["Rank"] = 28,["Kills"] = 4},
            ["Vault Warder"] = {["Rank"] = 29,["Kills"] = 4},
            ["Firemane Scalebane"] = {["Rank"] = 30,["Kills"] = 4},
            ["Scorpid Hunter"] = {["Rank"] = 31,["Kills"] = 4},
            ["Witherbark Felhunter"] = {["Rank"] = 32,["Kills"] = 4},
            ["Jaedenar Cultist"] = {["Rank"] = 33,["Kills"] = 4},
            ["Xalvic Blackclaw"] = {["Rank"] = 34,["Kills"] = 4},
            ["Crimson Courier"] = {["Rank"] = 35,["Kills"] = 4},
            ["Hive'Ashi Drone"] = {["Rank"] = 36,["Kills"] = 4},
            ["Konda"] = {["Rank"] = 37,["Kills"] = 3},
            ["Bloodsail Raider"] = {["Rank"] = 38,["Kills"] = 3},
            ["Fozruk"] = {["Rank"] = 39,["Kills"] = 3},
            ["Bloodsail Mage"] = {["Rank"] = 40,["Kills"] = 3},
            ["Maraudine Khan Guard"] = {["Rank"] = 41,["Kills"] = 3},
            ["Crushridge Warmonger"] = {["Rank"] = 42,["Kills"] = 3},
            ["Enraged Rock Elemental"] = {["Rank"] = 43,["Kills"] = 3},
            ["Mai'Zoth"] = {["Rank"] = 44,["Kills"] = 3},
            ["Daggerspine Raider"] = {["Rank"] = 45,["Kills"] = 3},
            ["Daggerspine Sorceress"] = {["Rank"] = 46,["Kills"] = 3},
            ["Marsh Inkspewer"] = {["Rank"] = 47,["Kills"] = 3},
            ["Green Wyrmkin"] = {["Rank"] = 48,["Kills"] = 3},
            ["Stonard Grunt"] = {["Rank"] = 49,["Kills"] = 3},
            ["Grimtotem Raider"] = {["Rank"] = 50,["Kills"] = 3},
            ["Bloodsail Deckhand"] = {["Rank"] = 51,["Kills"] = 3},
            ["Deathstrike Tarantula"] = {["Rank"] = 52,["Kills"] = 3},
            ["Wastewander Shadow Mage"] = {["Rank"] = 53,["Kills"] = 3},
            ["Blisterpaw Hyena"] = {["Rank"] = 54,["Kills"] = 3},
            ["Grimtotem Naturalist"] = {["Rank"] = 55,["Kills"] = 3},
            ["Wastewander Bandit"] = {["Rank"] = 56,["Kills"] = 3},
            ["Enraged Feral Scar"] = {["Rank"] = 57,["Kills"] = 3},
            ["Booty Bay Bruiser"] = {["Rank"] = 58,["Kills"] = 3},
            ["Silvermane Stalker"] = {["Rank"] = 59,["Kills"] = 3},
            ["Retherokk the Berserker"] = {["Rank"] = 60,["Kills"] = 3},
            ["Vile Priestess Hexx"] = {["Rank"] = 61,["Kills"] = 3},
            ["Vilebranch Raiding Wolf"] = {["Rank"] = 62,["Kills"] = 3},
            ["Dark Iron Slaver"] = {["Rank"] = 63,["Kills"] = 3},
            ["Devilsaur"] = {["Rank"] = 64,["Kills"] = 3},
            ["Un'Goro Thunderer"] = {["Rank"] = 65,["Kills"] = 3},
            ["Slavering Ghoul"] = {["Rank"] = 66,["Kills"] = 3},
            ["Scarlet Invoker"] = {["Rank"] = 67,["Kills"] = 3},
            ["Searing Ghoul"] = {["Rank"] = 68,["Kills"] = 3},
            ["Tyrant Devilsaur"] = {["Rank"] = 69,["Kills"] = 3},
            ["Faladar Starsplinter"] = {["Rank"] = 70,["Kills"] = 3},
            ["Cenarion Hold Infantry"] = {["Rank"] = 71,["Kills"] = 3},
            ["Crimson Bodyguard"] = {["Rank"] = 72,["Kills"] = 3},
            ["Shadowforge Warrior"] = {["Rank"] = 73,["Kills"] = 2},
            ["Mirefin Puddlejumper"] = {["Rank"] = 74,["Kills"] = 2},
            ["Starving Blisterpaw"] = {["Rank"] = 75,["Kills"] = 2},
            ["Bloodscalp Mystic"] = {["Rank"] = 76,["Kills"] = 2},
            ["Ridge Stalker"] = {["Rank"] = 77,["Kills"] = 2},
            ["Bhag'thera"] = {["Rank"] = 78,["Kills"] = 2},
            ["Outcast Necromancer"] = {["Rank"] = 79,["Kills"] = 2},
            ["Sprite Darter"] = {["Rank"] = 80,["Kills"] = 2},
            ["Deserter Turncoat"] = {["Rank"] = 81,["Kills"] = 2},
            ["Grovetender Engryss"] = {["Rank"] = 82,["Kills"] = 2},
            ["Grel'borg the Miser"] = {["Rank"] = 83,["Kills"] = 2},
            ["Deranged Ancient"] = {["Rank"] = 84,["Kills"] = 2},
            ["Scarlet Myrmidon"] = {["Rank"] = 85,["Kills"] = 2},
            ["Syndicate Prowler"] = {["Rank"] = 86,["Kills"] = 2},
            ["Boulderfist Lord"] = {["Rank"] = 87,["Kills"] = 2},
            ["Searing Whelp"] = {["Rank"] = 88,["Kills"] = 2},
            ["Ironpatch"] = {["Rank"] = 89,["Kills"] = 2},
            ["Gordunni Brute"] = {["Rank"] = 90,["Kills"] = 2},
            ["Gordunni Mauler"] = {["Rank"] = 91,["Kills"] = 2},
            ["Kurzen Subchief"] = {["Rank"] = 92,["Kills"] = 2},
            ["Darkmist Lurker"] = {["Rank"] = 93,["Kills"] = 2},
            ["Deserter Exile"] = {["Rank"] = 94,["Kills"] = 2},
            ["Elder Saltwater Crocolisk"] = {["Rank"] = 95,["Kills"] = 2},
            ["Scarlet Wizard"] = {["Rank"] = 96,["Kills"] = 2},
            ["Lord Shalzaru"] = {["Rank"] = 97,["Kills"] = 2},
            ["Wallowing Spirit"] = {["Rank"] = 98,["Kills"] = 2},
            ["Jaguero Stalker"] = {["Rank"] = 99,["Kills"] = 2},
            ["Mokk the Savage"] = {["Rank"] = 100,["Kills"] = 2},
        }
    end
end

function HCRank_players()
    return {
        ["Valkar"] = {["Rank"] = 1,["Kills"] = 143},
        ["Fleshbeard"] = {["Rank"] = 2,["Kills"] = 50},
        ["Zdraxus"] = {["Rank"] = 3,["Kills"] = 39},
        ["Greengnom"] = {["Rank"] = 4,["Kills"] = 35},
        ["Gevilgaz"] = {["Rank"] = 5,["Kills"] = 16},
        ["Lilrat"] = {["Rank"] = 6,["Kills"] = 14},
        ["Bamboozler"] = {["Rank"] = 7,["Kills"] = 12},
        ["Grimus"] = {["Rank"] = 8,["Kills"] = 12},
        ["Necrobeard"] = {["Rank"] = 9,["Kills"] = 12},
        ["Nytclaw"] = {["Rank"] = 10,["Kills"] = 11},
        ["Slimshadowy"] = {["Rank"] = 11,["Kills"] = 11},
        ["Chrisophia"] = {["Rank"] = 12,["Kills"] = 10},
        ["Dreadblade"] = {["Rank"] = 13,["Kills"] = 10},
        ["Shadist"] = {["Rank"] = 14,["Kills"] = 9},
        ["Dimkosyan"] = {["Rank"] = 15,["Kills"] = 8},
        ["Lichking"] = {["Rank"] = 16,["Kills"] = 8},
        ["Evolvz"] = {["Rank"] = 17,["Kills"] = 7},
        ["Deaddy"] = {["Rank"] = 18,["Kills"] = 7},
        ["Tuve"] = {["Rank"] = 19,["Kills"] = 7},
        ["Glin"] = {["Rank"] = 20,["Kills"] = 7},
        ["Stabby"] = {["Rank"] = 21,["Kills"] = 6},
        ["Zaradur"] = {["Rank"] = 22,["Kills"] = 6},
        ["Goblintoes"] = {["Rank"] = 23,["Kills"] = 6},
        ["Elkrinia"] = {["Rank"] = 24,["Kills"] = 6},
        ["Shmuckzo"] = {["Rank"] = 25,["Kills"] = 6},
        ["Nowpay"] = {["Rank"] = 26,["Kills"] = 5},
        ["Grovestalker"] = {["Rank"] = 27,["Kills"] = 5},
        ["Jimmycarrey"] = {["Rank"] = 28,["Kills"] = 5},
        ["Josalex"] = {["Rank"] = 29,["Kills"] = 5},
        ["Bye"] = {["Rank"] = 30,["Kills"] = 5},
        ["Yourmotherr"] = {["Rank"] = 31,["Kills"] = 5},
        ["Ripbozohaha"] = {["Rank"] = 32,["Kills"] = 5},
        ["Hordeath"] = {["Rank"] = 33,["Kills"] = 5},
        ["Doob"] = {["Rank"] = 34,["Kills"] = 5},
        ["Defiaspesant"] = {["Rank"] = 35,["Kills"] = 5},
        ["Naithan"] = {["Rank"] = 36,["Kills"] = 5},
        ["Wickedjaw"] = {["Rank"] = 37,["Kills"] = 5},
        ["Johnnydeath"] = {["Rank"] = 38,["Kills"] = 5},
        ["Yosemitesam"] = {["Rank"] = 39,["Kills"] = 5},
        ["Mangomazestv"] = {["Rank"] = 40,["Kills"] = 5},
        ["Proy"] = {["Rank"] = 41,["Kills"] = 5},
        ["Doomhandle"] = {["Rank"] = 42,["Kills"] = 5},
        ["Arium"] = {["Rank"] = 43,["Kills"] = 5},
        ["Nanachi"] = {["Rank"] = 44,["Kills"] = 4},
        ["Turzog"] = {["Rank"] = 45,["Kills"] = 4},
        ["Faralynn"] = {["Rank"] = 46,["Kills"] = 4},
        ["Pekora"] = {["Rank"] = 47,["Kills"] = 4},
        ["Minces"] = {["Rank"] = 48,["Kills"] = 4},
        ["Windtop"] = {["Rank"] = 49,["Kills"] = 4},
        ["Eemodru"] = {["Rank"] = 50,["Kills"] = 4},
        ["Grizzlie"] = {["Rank"] = 51,["Kills"] = 4},
        ["Megalomaniac"] = {["Rank"] = 52,["Kills"] = 4},
        ["Grimbatuul"] = {["Rank"] = 53,["Kills"] = 4},
        ["Zilberman"] = {["Rank"] = 54,["Kills"] = 4},
        ["Ysomad"] = {["Rank"] = 55,["Kills"] = 4},
        ["Aldielshala"] = {["Rank"] = 56,["Kills"] = 4},
        ["Watame"] = {["Rank"] = 57,["Kills"] = 4},
        ["Exukor"] = {["Rank"] = 58,["Kills"] = 3},
        ["Tipsniffer"] = {["Rank"] = 59,["Kills"] = 3},
        ["Flardy"] = {["Rank"] = 60,["Kills"] = 3},
        ["Shacklez"] = {["Rank"] = 61,["Kills"] = 3},
        ["Mossadagent"] = {["Rank"] = 62,["Kills"] = 3},
        ["Greenpepe"] = {["Rank"] = 63,["Kills"] = 3},
        ["Jabun"] = {["Rank"] = 64,["Kills"] = 3},
        ["Abwxo"] = {["Rank"] = 65,["Kills"] = 3},
        ["Hettaku"] = {["Rank"] = 66,["Kills"] = 3},
        ["Cele"] = {["Rank"] = 67,["Kills"] = 3},
        ["Nyatka"] = {["Rank"] = 68,["Kills"] = 3},
        ["Zaas"] = {["Rank"] = 69,["Kills"] = 3},
        ["Bopka"] = {["Rank"] = 70,["Kills"] = 3},
        ["Rwby"] = {["Rank"] = 71,["Kills"] = 3},
        ["Nestro"] = {["Rank"] = 72,["Kills"] = 3},
        ["Rhazhai"] = {["Rank"] = 73,["Kills"] = 3},
        ["Liviid"] = {["Rank"] = 74,["Kills"] = 3},
        ["Bunkerfaust"] = {["Rank"] = 75,["Kills"] = 3},
        ["Warmodekilla"] = {["Rank"] = 76,["Kills"] = 3},
        ["Bonah"] = {["Rank"] = 77,["Kills"] = 3},
        ["Caryww"] = {["Rank"] = 78,["Kills"] = 2},
        ["Maeryll"] = {["Rank"] = 79,["Kills"] = 2},
        ["Gungner"] = {["Rank"] = 80,["Kills"] = 2},
        ["Delerius"] = {["Rank"] = 81,["Kills"] = 2},
        ["Evilscum"] = {["Rank"] = 82,["Kills"] = 2},
        ["Zarken"] = {["Rank"] = 83,["Kills"] = 2},
        ["Mugoska"] = {["Rank"] = 84,["Kills"] = 2},
        ["Zerodos"] = {["Rank"] = 85,["Kills"] = 2},
        ["Whush"] = {["Rank"] = 86,["Kills"] = 2},
        ["Cuchillada"] = {["Rank"] = 87,["Kills"] = 2},
        ["Bloats"] = {["Rank"] = 88,["Kills"] = 2},
        ["Ghibis"] = {["Rank"] = 89,["Kills"] = 2},
        ["Oneill"] = {["Rank"] = 90,["Kills"] = 2},
        ["Podpivas"] = {["Rank"] = 91,["Kills"] = 2},
        ["Haavoc"] = {["Rank"] = 92,["Kills"] = 2},
        ["Phuqqinrun"] = {["Rank"] = 93,["Kills"] = 2},
        ["Bigginz"] = {["Rank"] = 94,["Kills"] = 2},
        ["Andergor"] = {["Rank"] = 95,["Kills"] = 2},
        ["Olinson"] = {["Rank"] = 96,["Kills"] = 2},
        ["Iag"] = {["Rank"] = 97,["Kills"] = 2},
        ["Arkimonday"] = {["Rank"] = 98,["Kills"] = 2},
        ["Artnizarka"] = {["Rank"] = 99,["Kills"] = 2},
        ["Gudreang"] = {["Rank"] = 100,["Kills"] = 2},
    }
end