function HCRank_mobs(level)
    if level <= 20 then
        return {
            ["Defias Bodyguard"] = {["Rank"] = 1,["Kills"] = 501},
            ["Defias Highwayman"] = {["Rank"] = 2,["Kills"] = 367},
            ["Defias Trapper"] = {["Rank"] = 3,["Kills"] = 349},
            ["Rockjaw Bonesnapper"] = {["Rank"] = 4,["Kills"] = 234},
            ["Tunnel Rat Geomancer"] = {["Rank"] = 5,["Kills"] = 174},
            ["Vagash"] = {["Rank"] = 6,["Kills"] = 152},
            ["Defias Pillager"] = {["Rank"] = 7,["Kills"] = 150},
            ["Rotting Ancestor"] = {["Rank"] = 8,["Kills"] = 138},
            ["Defias Looter"] = {["Rank"] = 9,["Kills"] = 137},
            ["Sunscale Scytheclaw"] = {["Rank"] = 10,["Kills"] = 133},
            ["Lunaclaw"] = {["Rank"] = 11,["Kills"] = 131},
            ["Voidwalker"] = {["Rank"] = 12,["Kills"] = 131},
            ["Riverpaw Outrunner"] = {["Rank"] = 13,["Kills"] = 127},
            ["Son of Arugal"] = {["Rank"] = 14,["Kills"] = 118},
            ["Burning Blade Toxicologist"] = {["Rank"] = 15,["Kills"] = 117},
            ["Benny Blaanco"] = {["Rank"] = 16,["Kills"] = 116},
            ["Burning Blade Apprentice"] = {["Rank"] = 17,["Kills"] = 115},
            ["Warlord Krom'zar"] = {["Rank"] = 18,["Kills"] = 115},
            ["Bristleback Trapper"] = {["Rank"] = 19,["Kills"] = 111},
            ["Tunnel Rat Kobold"] = {["Rank"] = 20,["Kills"] = 110},
            ["Carver Molsen"] = {["Rank"] = 21,["Kills"] = 108},
            ["Fizzle Darkstorm"] = {["Rank"] = 22,["Kills"] = 107},
            ["Razormane Defender"] = {["Rank"] = 23,["Kills"] = 107},
            ["Riverpaw Bandit"] = {["Rank"] = 24,["Kills"] = 104},
            ["Harvest Watcher"] = {["Rank"] = 25,["Kills"] = 101},
            ["Dreadmaw Crocolisk"] = {["Rank"] = 26,["Kills"] = 97},
            ["Longsnout"] = {["Rank"] = 27,["Kills"] = 94},
            ["Stonesplinter Trogg"] = {["Rank"] = 28,["Kills"] = 93},
            ["Stormscale Wave Rider"] = {["Rank"] = 29,["Kills"] = 90},
            ["Tunnel Rat Digger"] = {["Rank"] = 30,["Kills"] = 88},
            ["Venture Co. Enforcer"] = {["Rank"] = 31,["Kills"] = 88},
            ["Defias Smuggler"] = {["Rank"] = 32,["Kills"] = 87},
            ["Stonesplinter Skullthumper"] = {["Rank"] = 33,["Kills"] = 85},
            ["Witchwing Slayer"] = {["Rank"] = 34,["Kills"] = 83},
            ["Tunnel Rat Forager"] = {["Rank"] = 35,["Kills"] = 81},
            ["Murloc Coastrunner"] = {["Rank"] = 36,["Kills"] = 77},
            ["Blackrock Outrunner"] = {["Rank"] = 37,["Kills"] = 77},
            ["Ol' Sooty"] = {["Rank"] = 38,["Kills"] = 73},
            ["Defias Pathstalker"] = {["Rank"] = 39,["Kills"] = 72},
            ["Murloc Tidehunter"] = {["Rank"] = 40,["Kills"] = 71},
            ["Hecklefang Hyena"] = {["Rank"] = 41,["Kills"] = 68},
            ["Theramore Marine"] = {["Rank"] = 42,["Kills"] = 68},
            ["Stonesplinter Seer"] = {["Rank"] = 43,["Kills"] = 66},
            ["Kolkar Invader"] = {["Rank"] = 44,["Kills"] = 63},
            ["Imp Minion"] = {["Rank"] = 45,["Kills"] = 62},
            ["Gnarlpine Shaman"] = {["Rank"] = 46,["Kills"] = 62},
            ["Sand Shark"] = {["Rank"] = 47,["Kills"] = 62},
            ["Gnarlpine Defender"] = {["Rank"] = 48,["Kills"] = 61},
            ["Lillith Nefara"] = {["Rank"] = 49,["Kills"] = 60},
            ["Ragefire Trogg"] = {["Rank"] = 50,["Kills"] = 60},
            ["Riverpaw Brute"] = {["Rank"] = 51,["Kills"] = 60},
            ["Venture Co. Overseer"] = {["Rank"] = 52,["Kills"] = 60},
            ["Raging Moonkin"] = {["Rank"] = 53,["Kills"] = 59},
            ["Defias Knuckleduster"] = {["Rank"] = 54,["Kills"] = 59},
            ["Kodo Matriarch"] = {["Rank"] = 55,["Kills"] = 57},
            ["Defias Bandit"] = {["Rank"] = 56,["Kills"] = 56},
            ["Carnivous the Breaker"] = {["Rank"] = 57,["Kills"] = 55},
            ["Deepmoss Matriarch"] = {["Rank"] = 58,["Kills"] = 55},
            ["Razormane Water Seeker"] = {["Rank"] = 59,["Kills"] = 54},
            ["Expedition Commando"] = {["Rank"] = 60,["Kills"] = 53},
            ["Burning Blade Fanatic"] = {["Rank"] = 61,["Kills"] = 53},
            ["Dire Condor"] = {["Rank"] = 62,["Kills"] = 53},
            ["Gazz'uz"] = {["Rank"] = 63,["Kills"] = 49},
            ["Murloc Netter"] = {["Rank"] = 64,["Kills"] = 49},
            ["Old Icebeard"] = {["Rank"] = 65,["Kills"] = 47},
            ["Taskmaster Fizzule"] = {["Rank"] = 66,["Kills"] = 47},
            ["Foreman Grills"] = {["Rank"] = 67,["Kills"] = 47},
            ["Prowler"] = {["Rank"] = 68,["Kills"] = 46},
            ["Stonesplinter Scout"] = {["Rank"] = 69,["Kills"] = 46},
            ["Oggleflint"] = {["Rank"] = 70,["Kills"] = 45},
            ["Rockjaw Skullthumper"] = {["Rank"] = 71,["Kills"] = 44},
            ["Moonstalker Runt"] = {["Rank"] = 72,["Kills"] = 44},
            ["Kolkar Packhound"] = {["Rank"] = 73,["Kills"] = 44},
            ["Stormscale Siren"] = {["Rank"] = 74,["Kills"] = 44},
            ["Moonrage Darksoul"] = {["Rank"] = 75,["Kills"] = 43},
            ["Southsea Cannoneer"] = {["Rank"] = 76,["Kills"] = 43},
            ["Venture Co. Drudger"] = {["Rank"] = 77,["Kills"] = 43},
            ["Witchwing Roguefeather"] = {["Rank"] = 78,["Kills"] = 43},
            ["Verog the Dervish"] = {["Rank"] = 79,["Kills"] = 43},
            ["Hogger"] = {["Rank"] = 80,["Kills"] = 42},
            ["Greymist Coastrunner"] = {["Rank"] = 81,["Kills"] = 42},
            ["Stonesplinter Bonesnapper"] = {["Rank"] = 82,["Kills"] = 42},
            ["Polly"] = {["Rank"] = 83,["Kills"] = 42},
            ["Gnarlpine Augur"] = {["Rank"] = 84,["Kills"] = 41},
            ["Coyote"] = {["Rank"] = 85,["Kills"] = 40},
            ["Foe Reaper 4000"] = {["Rank"] = 86,["Kills"] = 40},
            ["Defias Dockmaster"] = {["Rank"] = 87,["Kills"] = 39},
            ["Stonesplinter Shaman"] = {["Rank"] = 88,["Kills"] = 39},
            ["Dalaran Serpent"] = {["Rank"] = 89,["Kills"] = 39},
            ["Bristleback Hunter"] = {["Rank"] = 90,["Kills"] = 39},
            ["Goretusk"] = {["Rank"] = 91,["Kills"] = 38},
            ["Murloc Oracle"] = {["Rank"] = 92,["Kills"] = 38},
            ["Venture Co. Supervisor"] = {["Rank"] = 93,["Kills"] = 37},
            ["Ornery Plainstrider"] = {["Rank"] = 94,["Kills"] = 36},
            ["Bristleback Thornweaver"] = {["Rank"] = 95,["Kills"] = 36},
            ["Compact Harvest Reaper"] = {["Rank"] = 96,["Kills"] = 36},
            ["Dustwind Storm Witch"] = {["Rank"] = 97,["Kills"] = 35},
            ["Venomtail Scorpid"] = {["Rank"] = 98,["Kills"] = 35},
            ["Minion of Sethir"] = {["Rank"] = 99,["Kills"] = 35},
            ["Blackmoss the Fetid"] = {["Rank"] = 100,["Kills"] = 34},
        }
    elseif level <= 30 then
        return {
            ["Deepmoss Matriarch"] = {["Rank"] = 1,["Kills"] = 111},
            ["Stitches"] = {["Rank"] = 2,["Kills"] = 72},
            ["Compact Harvest Reaper"] = {["Rank"] = 3,["Kills"] = 70},
            ["Razormane Stalker"] = {["Rank"] = 4,["Kills"] = 51},
            ["Unseen"] = {["Rank"] = 5,["Kills"] = 40},
            ["Carver Molsen"] = {["Rank"] = 6,["Kills"] = 37},
            ["Dark Strand Assassin"] = {["Rank"] = 7,["Kills"] = 37},
            ["Mor'Ladim"] = {["Rank"] = 8,["Kills"] = 37},
            ["Silithid Swarm"] = {["Rank"] = 9,["Kills"] = 34},
            ["Shadowhide Slayer"] = {["Rank"] = 10,["Kills"] = 32},
            ["Wretched Bodyguard"] = {["Rank"] = 11,["Kills"] = 32},
            ["Blackrock Sentry"] = {["Rank"] = 12,["Kills"] = 32},
            ["Dragonmaw Raider"] = {["Rank"] = 13,["Kills"] = 32},
            ["Blackrock Champion"] = {["Rank"] = 14,["Kills"] = 28},
            ["Blackrock Outrunner"] = {["Rank"] = 15,["Kills"] = 26},
            ["Goggeroc"] = {["Rank"] = 16,["Kills"] = 26},
            ["Defias Blackguard"] = {["Rank"] = 17,["Kills"] = 25},
            ["Hillsbrad Miner"] = {["Rank"] = 18,["Kills"] = 22},
            ["Defias Raider"] = {["Rank"] = 19,["Kills"] = 21},
            ["Wildthorn Lurker"] = {["Rank"] = 20,["Kills"] = 21},
            ["Galak Assassin"] = {["Rank"] = 21,["Kills"] = 21},
            ["Warlord Krom'zar"] = {["Rank"] = 22,["Kills"] = 20},
            ["Deepmoss Creeper"] = {["Rank"] = 23,["Kills"] = 20},
            ["Defias Pirate"] = {["Rank"] = 24,["Kills"] = 20},
            ["Bloodfury Ripper"] = {["Rank"] = 25,["Kills"] = 20},
            ["Defias Digger"] = {["Rank"] = 26,["Kills"] = 19},
            ["Grunt"] = {["Rank"] = 27,["Kills"] = 19},
            ["Bael'dun Officer"] = {["Rank"] = 28,["Kills"] = 19},
            ["Aku'mai Snapjaw"] = {["Rank"] = 29,["Kills"] = 19},
            ["Deviate Creeper"] = {["Rank"] = 30,["Kills"] = 18},
            ["Defias Overseer"] = {["Rank"] = 31,["Kills"] = 18},
            ["Chok'sul"] = {["Rank"] = 32,["Kills"] = 18},
            ["Shadowhide Brute"] = {["Rank"] = 33,["Kills"] = 18},
            ["Cursed Sailor"] = {["Rank"] = 34,["Kills"] = 18},
            ["Edwin VanCleef"] = {["Rank"] = 35,["Kills"] = 17},
            ["Blackrock Summoner"] = {["Rank"] = 36,["Kills"] = 17},
            ["Defias Highwayman"] = {["Rank"] = 37,["Kills"] = 17},
            ["Bael'dun Foreman"] = {["Rank"] = 38,["Kills"] = 16},
            ["Black Widow Hatchling"] = {["Rank"] = 39,["Kills"] = 16},
            ["Silithid Grub"] = {["Rank"] = 40,["Kills"] = 16},
            ["Devouring Ectoplasm"] = {["Rank"] = 41,["Kills"] = 16},
            ["Dun Garok Soldier"] = {["Rank"] = 42,["Kills"] = 16},
            ["Dragonmaw Grunt"] = {["Rank"] = 43,["Kills"] = 15},
            ["Befouled Water Elemental"] = {["Rank"] = 44,["Kills"] = 15},
            ["Nightbane Dark Runner"] = {["Rank"] = 45,["Kills"] = 15},
            ["Bloodfury Ambusher"] = {["Rank"] = 46,["Kills"] = 15},
            ["Bleak Worg"] = {["Rank"] = 47,["Kills"] = 15},
            ["Syndicate Watchman"] = {["Rank"] = 48,["Kills"] = 14},
            ["Venture Co. Enforcer"] = {["Rank"] = 49,["Kills"] = 14},
            ["Druid of the Fang"] = {["Rank"] = 50,["Kills"] = 14},
            ["Besseleth"] = {["Rank"] = 51,["Kills"] = 14},
            ["Ol' Sooty"] = {["Rank"] = 52,["Kills"] = 14},
            ["Bael'dun Excavator"] = {["Rank"] = 53,["Kills"] = 14},
            ["Flesh Eating Worm"] = {["Rank"] = 54,["Kills"] = 14},
            ["Redridge Basher"] = {["Rank"] = 55,["Kills"] = 13},
            ["Silithid Swarmer"] = {["Rank"] = 56,["Kills"] = 13},
            ["Defias Squallshaper"] = {["Rank"] = 57,["Kills"] = 13},
            ["Nightbane Shadow Weaver"] = {["Rank"] = 58,["Kills"] = 13},
            ["Defias Rioter"] = {["Rank"] = 59,["Kills"] = 13},
            ["Horde Guard"] = {["Rank"] = 60,["Kills"] = 12},
            ["Blackrock Gladiator"] = {["Rank"] = 61,["Kills"] = 12},
            ["Blackrock Shadowcaster"] = {["Rank"] = 62,["Kills"] = 12},
            ["Blackrock Tracker"] = {["Rank"] = 63,["Kills"] = 12},
            ["Slavering Worg"] = {["Rank"] = 64,["Kills"] = 12},
            ["Cursed Marine"] = {["Rank"] = 65,["Kills"] = 12},
            ["Defias Inmate"] = {["Rank"] = 66,["Kills"] = 12},
            ["Deviate Dreadfang"] = {["Rank"] = 67,["Kills"] = 11},
            ["Greymist Coastrunner"] = {["Rank"] = 68,["Kills"] = 11},
            ["Marcus Bel"] = {["Rank"] = 69,["Kills"] = 11},
            ["Deepmoss Hatchling"] = {["Rank"] = 70,["Kills"] = 11},
            ["Taskmaster Fizzule"] = {["Rank"] = 71,["Kills"] = 11},
            ["Redridge Alpha"] = {["Rank"] = 72,["Kills"] = 11},
            ["Mosshide Mongrel"] = {["Rank"] = 73,["Kills"] = 11},
            ["Remnants Footman"] = {["Rank"] = 74,["Kills"] = 11},
            ["Defias Night Blade"] = {["Rank"] = 75,["Kills"] = 11},
            ["Bone Chewer"] = {["Rank"] = 76,["Kills"] = 11},
            ["Lupine Horror"] = {["Rank"] = 77,["Kills"] = 11},
            ["Ruuzel"] = {["Rank"] = 78,["Kills"] = 10},
            ["Bristleback Thornweaver"] = {["Rank"] = 79,["Kills"] = 10},
            ["Wandering Protector"] = {["Rank"] = 80,["Kills"] = 10},
            ["Crimson Ooze"] = {["Rank"] = 81,["Kills"] = 10},
            ["Skeletal Horror"] = {["Rank"] = 82,["Kills"] = 10},
            ["Windshear Digger"] = {["Rank"] = 83,["Kills"] = 10},
            ["Eliza's Guard"] = {["Rank"] = 84,["Kills"] = 10},
            ["Hillsbrad Peasant"] = {["Rank"] = 85,["Kills"] = 10},
            ["Lupine Delusion"] = {["Rank"] = 86,["Kills"] = 10},
            ["Wrathtail Sea Witch"] = {["Rank"] = 87,["Kills"] = 9},
            ["Shadowhide Warrior"] = {["Rank"] = 88,["Kills"] = 9},
            ["Venture Co. Overseer"] = {["Rank"] = 89,["Kills"] = 9},
            ["Necromancer Reginald"] = {["Rank"] = 90,["Kills"] = 9},
            ["Kolkar Invader"] = {["Rank"] = 91,["Kills"] = 9},
            ["Skeletal Miner"] = {["Rank"] = 92,["Kills"] = 9},
            ["Hannah Bladeleaf"] = {["Rank"] = 93,["Kills"] = 9},
            ["Gogger Rock Keeper"] = {["Rank"] = 94,["Kills"] = 9},
            ["Defias Henchman"] = {["Rank"] = 95,["Kills"] = 9},
            ["Taskmaster Whipfang"] = {["Rank"] = 96,["Kills"] = 9},
            ["Rorgish Jowl"] = {["Rank"] = 97,["Kills"] = 9},
            ["Syndicate Rogue"] = {["Rank"] = 98,["Kills"] = 9},
            ["Hillsbrad Foreman"] = {["Rank"] = 99,["Kills"] = 9},
            ["Plague Spreader"] = {["Rank"] = 100,["Kills"] = 9},
        }
    elseif level <= 40 then
        return {
            ["Blastmaster Emi Shortfuse"] = {["Rank"] = 1,["Kills"] = 29},
            ["Unseen"] = {["Rank"] = 2,["Kills"] = 28},
            ["Undead Ravager"] = {["Rank"] = 3,["Kills"] = 17},
            ["Warleader Kintoza"] = {["Rank"] = 4,["Kills"] = 17},
            ["Kurzen Commando"] = {["Rank"] = 5,["Kills"] = 16},
            ["Magrami Spectre"] = {["Rank"] = 6,["Kills"] = 14},
            ["Dragonmaw Raider"] = {["Rank"] = 7,["Kills"] = 12},
            ["Witherbark Headhunter"] = {["Rank"] = 8,["Kills"] = 12},
            ["Slim's Friend"] = {["Rank"] = 9,["Kills"] = 11},
            ["Deranged Ancient"] = {["Rank"] = 10,["Kills"] = 11},
            ["Burning Blade Felsworn"] = {["Rank"] = 11,["Kills"] = 9},
            ["Grenka Bloodscreech"] = {["Rank"] = 12,["Kills"] = 8},
            ["Southshore Guard"] = {["Rank"] = 13,["Kills"] = 8},
            ["Nightbane Dark Runner"] = {["Rank"] = 14,["Kills"] = 8},
            ["Tarren Mill Deathguard"] = {["Rank"] = 15,["Kills"] = 8},
            ["Bloodscalp Scout"] = {["Rank"] = 16,["Kills"] = 8},
            ["Barrens Guard"] = {["Rank"] = 17,["Kills"] = 7},
            ["Screeching Harpy"] = {["Rank"] = 18,["Kills"] = 7},
            ["Scarlet Monk"] = {["Rank"] = 19,["Kills"] = 7},
            ["Syndicate Prowler"] = {["Rank"] = 20,["Kills"] = 7},
            ["Mosh'Ogg Warmonger"] = {["Rank"] = 21,["Kills"] = 7},
            ["Saltscale Oracle"] = {["Rank"] = 22,["Kills"] = 7},
            ["Darkmist Silkspinner"] = {["Rank"] = 23,["Kills"] = 7},
            ["Vile Sting"] = {["Rank"] = 24,["Kills"] = 6},
            ["Hillsbrad Miner"] = {["Rank"] = 25,["Kills"] = 6},
            ["Kolkar Destroyer"] = {["Rank"] = 26,["Kills"] = 6},
            ["Syndicate Thief"] = {["Rank"] = 27,["Kills"] = 6},
            ["Elder Saltwater Crocolisk"] = {["Rank"] = 28,["Kills"] = 6},
            ["Dun Garok Mountaineer"] = {["Rank"] = 29,["Kills"] = 6},
            ["Dun Garok Soldier"] = {["Rank"] = 30,["Kills"] = 5},
            ["Scorpid Reaver"] = {["Rank"] = 31,["Kills"] = 5},
            ["Syndicate Wizard"] = {["Rank"] = 32,["Kills"] = 5},
            ["Hammerfall Peon"] = {["Rank"] = 33,["Kills"] = 5},
            ["Scarlet Gallant"] = {["Rank"] = 34,["Kills"] = 5},
            ["Witherbark Rogue"] = {["Rank"] = 35,["Kills"] = 5},
            ["Scarlet Myrmidon"] = {["Rank"] = 36,["Kills"] = 5},
            ["Dark Iron Tunneler"] = {["Rank"] = 37,["Kills"] = 4},
            ["Stitches"] = {["Rank"] = 38,["Kills"] = 4},
            ["Scarlet Torturer"] = {["Rank"] = 39,["Kills"] = 4},
            ["Old Town Thug"] = {["Rank"] = 40,["Kills"] = 4},
            ["Chieftain Nek'rosh"] = {["Rank"] = 41,["Kills"] = 4},
            ["Aku'mai Snapjaw"] = {["Rank"] = 42,["Kills"] = 4},
            ["Dalaran Shield Guard"] = {["Rank"] = 43,["Kills"] = 4},
            ["Magus Palon"] = {["Rank"] = 44,["Kills"] = 4},
            ["Mor'Ladim"] = {["Rank"] = 45,["Kills"] = 4},
            ["Stromgarde Cavalryman"] = {["Rank"] = 46,["Kills"] = 4},
            ["Kovork"] = {["Rank"] = 47,["Kills"] = 4},
            ["Mechanized Guardian"] = {["Rank"] = 48,["Kills"] = 4},
            ["Crushridge Mauler"] = {["Rank"] = 49,["Kills"] = 4},
            ["Drywhisker Digger"] = {["Rank"] = 50,["Kills"] = 4},
            ["Drywallow Vicejaw"] = {["Rank"] = 51,["Kills"] = 4},
            ["Saltscale Warrior"] = {["Rank"] = 52,["Kills"] = 4},
            ["Maraudine Bonepaw"] = {["Rank"] = 53,["Kills"] = 4},
            ["Galak Assassin"] = {["Rank"] = 54,["Kills"] = 3},
            ["Dalaran Theurgist"] = {["Rank"] = 55,["Kills"] = 3},
            ['Tapoke "Slim" Jahn'] = {["Rank"] = 56,["Kills"] = 3},
            ["Highland Thrasher"] = {["Rank"] = 57,["Kills"] = 3},
            ["Morbent Fel"] = {["Rank"] = 58,["Kills"] = 3},
            ["Skeleton"] = {["Rank"] = 59,["Kills"] = 3},
            ["Bael'dun Officer"] = {["Rank"] = 60,["Kills"] = 3},
            ["Balgaras the Foul"] = {["Rank"] = 61,["Kills"] = 3},
            ["Torn Fin Tidehunter"] = {["Rank"] = 62,["Kills"] = 3},
            ["Dark Iron Demolitionist"] = {["Rank"] = 63,["Kills"] = 3},
            ["Harlus Ashbuckle"] = {["Rank"] = 64,["Kills"] = 3},
            ["Defias Convict"] = {["Rank"] = 65,["Kills"] = 3},
            ["Saltstone Crystalhide"] = {["Rank"] = 66,["Kills"] = 3},
            ["Captain Ironhill"] = {["Rank"] = 67,["Kills"] = 3},
            ["Defias Rioter"] = {["Rank"] = 68,["Kills"] = 3},
            ["Kurzen War Tiger"] = {["Rank"] = 69,["Kills"] = 3},
            ["Scarlet Beastmaster"] = {["Rank"] = 70,["Kills"] = 3},
            ["Holdout Medic"] = {["Rank"] = 71,["Kills"] = 3},
            ["Kurzen Jungle Fighter"] = {["Rank"] = 72,["Kills"] = 3},
            ["Maraudine Wrangler"] = {["Rank"] = 73,["Kills"] = 3},
            ["Bloodscalp Hunter"] = {["Rank"] = 74,["Kills"] = 3},
            ["Drywallow Daggermaw"] = {["Rank"] = 75,["Kills"] = 3},
            ["Bhag'thera"] = {["Rank"] = 76,["Kills"] = 3},
            ["Witherbark Raider"] = {["Rank"] = 77,["Kills"] = 3},
            ["Darkmist Lurker"] = {["Rank"] = 78,["Kills"] = 3},
            ["Sorrow Spinner"] = {["Rank"] = 79,["Kills"] = 3},
            ["Bloodsail Raider"] = {["Rank"] = 80,["Kills"] = 3},
            ["Witherbark Darkcaller"] = {["Rank"] = 81,["Kills"] = 3},
            ["Bloodscalp Mystic"] = {["Rank"] = 82,["Kills"] = 3},
            ["Tethis"] = {["Rank"] = 83,["Kills"] = 3},
            ["Stonard Grunt"] = {["Rank"] = 84,["Kills"] = 3},
            ["Helcular's Remains"] = {["Rank"] = 85,["Kills"] = 2},
            ["Voidwalker"] = {["Rank"] = 86,["Kills"] = 2},
            ["Defias Prisoner"] = {["Rank"] = 87,["Kills"] = 2},
            ["Boulderfist Enforcer"] = {["Rank"] = 88,["Kills"] = 2},
            ["Swamp Jaguar"] = {["Rank"] = 89,["Kills"] = 2},
            ["Felguard"] = {["Rank"] = 90,["Kills"] = 2},
            ["Shadowhide Slayer"] = {["Rank"] = 91,["Kills"] = 2},
            ["Slavering Worg"] = {["Rank"] = 92,["Kills"] = 2},
            ["Bael'dun Soldier"] = {["Rank"] = 93,["Kills"] = 2},
            ["Scarlet Adept"] = {["Rank"] = 94,["Kills"] = 2},
            ["Razorfen Thornweaver"] = {["Rank"] = 95,["Kills"] = 2},
            ["Thanthaldis Snowgleam"] = {["Rank"] = 96,["Kills"] = 2},
            ["Razorfen Spearhide"] = {["Rank"] = 97,["Kills"] = 2},
            ["Scarlet Chaplain"] = {["Rank"] = 98,["Kills"] = 2},
            ["Addled Leper"] = {["Rank"] = 99,["Kills"] = 2},
            ["Crystal Spine Basilisk"] = {["Rank"] = 100,["Kills"] = 2},
        }
    elseif level <= 59 then
        return {
            ["Fleet Master Firallon"] = {["Rank"] = 1,["Kills"] = 13},
            ["Firemane Ash Tail"] = {["Rank"] = 2,["Kills"] = 9},
            ["Firemane Scout"] = {["Rank"] = 3,["Kills"] = 7},
            ["Khan Hratha"] = {["Rank"] = 4,["Kills"] = 6},
            ["Magrami Spectre"] = {["Rank"] = 5,["Kills"] = 6},
            ["Wastewander Assassin"] = {["Rank"] = 6,["Kills"] = 6},
            ["Vilebranch Kidnapper"] = {["Rank"] = 7,["Kills"] = 6},
            ["Fallen Hero"] = {["Rank"] = 8,["Kills"] = 6},
            ["Grol the Destroyer"] = {["Rank"] = 9,["Kills"] = 5},
            ["Undead Ravager"] = {["Rank"] = 10,["Kills"] = 4},
            ["Maraudine Wrangler"] = {["Rank"] = 11,["Kills"] = 4},
            ["Scorpid Hunter"] = {["Rank"] = 12,["Kills"] = 4},
            ["Hatecrest Serpent Guard"] = {["Rank"] = 13,["Kills"] = 4},
            ["Jaedenar Adept"] = {["Rank"] = 14,["Kills"] = 4},
            ["Gorishi Hive Guard"] = {["Rank"] = 15,["Kills"] = 4},
            ["Hive'Ashi Drone"] = {["Rank"] = 16,["Kills"] = 4},
            ["Konda"] = {["Rank"] = 17,["Kills"] = 3},
            ["Drywallow Daggermaw"] = {["Rank"] = 18,["Kills"] = 3},
            ["Bloodsail Mage"] = {["Rank"] = 19,["Kills"] = 3},
            ["Vault Warder"] = {["Rank"] = 20,["Kills"] = 3},
            ["Bloodsail Elder Magus"] = {["Rank"] = 21,["Kills"] = 3},
            ["Scalebane Captain"] = {["Rank"] = 22,["Kills"] = 3},
            ["Somnus"] = {["Rank"] = 23,["Kills"] = 3},
            ["Witherbark Felhunter"] = {["Rank"] = 24,["Kills"] = 3},
            ["Enraged Feral Scar"] = {["Rank"] = 25,["Kills"] = 3},
            ["Vilebranch Raiding Wolf"] = {["Rank"] = 26,["Kills"] = 3},
            ["Xalvic Blackclaw"] = {["Rank"] = 27,["Kills"] = 3},
            ["Cenarion Hold Infantry"] = {["Rank"] = 28,["Kills"] = 3},
            ["Bloodsail Raider"] = {["Rank"] = 29,["Kills"] = 2},
            ["Starving Blisterpaw"] = {["Rank"] = 30,["Kills"] = 2},
            ["Enraged Silverback Gorilla"] = {["Rank"] = 31,["Kills"] = 2},
            ["Deserter Turncoat"] = {["Rank"] = 32,["Kills"] = 2},
            ["Grovetender Engryss"] = {["Rank"] = 33,["Kills"] = 2},
            ["Fozruk"] = {["Rank"] = 34,["Kills"] = 2},
            ["Bloodscalp Mystic"] = {["Rank"] = 35,["Kills"] = 2},
            ["Sprite Darter"] = {["Rank"] = 36,["Kills"] = 2},
            ["Ridge Stalker"] = {["Rank"] = 37,["Kills"] = 2},
            ["Bloodsail Sea Dog"] = {["Rank"] = 38,["Kills"] = 2},
            ["Ironpatch"] = {["Rank"] = 39,["Kills"] = 2},
            ["Mosh'Ogg Warmonger"] = {["Rank"] = 40,["Kills"] = 2},
            ["Stonard Grunt"] = {["Rank"] = 41,["Kills"] = 2},
            ["Elder Saltwater Crocolisk"] = {["Rank"] = 42,["Kills"] = 2},
            ["Enraged Rock Elemental"] = {["Rank"] = 43,["Kills"] = 2},
            ["Mokk the Savage"] = {["Rank"] = 44,["Kills"] = 2},
            ["Blisterpaw Hyena"] = {["Rank"] = 45,["Kills"] = 2},
            ["Zetharia"] = {["Rank"] = 46,["Kills"] = 2},
            ["Grimtotem Naturalist"] = {["Rank"] = 47,["Kills"] = 2},
            ["Zul'Farrak Zombie"] = {["Rank"] = 48,["Kills"] = 2},
            ["Booty Bay Bruiser"] = {["Rank"] = 49,["Kills"] = 2},
            ["Stonevault Mauler"] = {["Rank"] = 50,["Kills"] = 2},
            ["Shay Leafrunner"] = {["Rank"] = 51,["Kills"] = 2},
            ["Vile Priestess Hexx"] = {["Rank"] = 52,["Kills"] = 2},
            ["Gammerita"] = {["Rank"] = 53,["Kills"] = 2},
            ["Un'Goro Thunderer"] = {["Rank"] = 54,["Kills"] = 2},
            ["Silvermane Stalker"] = {["Rank"] = 55,["Kills"] = 2},
            ["Stegodon"] = {["Rank"] = 56,["Kills"] = 2},
            ["Jaedenar Cultist"] = {["Rank"] = 57,["Kills"] = 2},
            ["King Mosh"] = {["Rank"] = 58,["Kills"] = 2},
            ["Scarlet Invoker"] = {["Rank"] = 59,["Kills"] = 2},
            ["Searing Ghoul"] = {["Rank"] = 60,["Kills"] = 2},
            ["Slavering Ghoul"] = {["Rank"] = 61,["Kills"] = 2},
            ["The Cleaner"] = {["Rank"] = 62,["Kills"] = 2},
            ["Watery Invader"] = {["Rank"] = 63,["Kills"] = 2},
            ["Felguard Elite"] = {["Rank"] = 64,["Kills"] = 2},
            ["Crimson Bodyguard"] = {["Rank"] = 65,["Kills"] = 2},
            ["Shadowforge Warrior"] = {["Rank"] = 66,["Kills"] = 1},
            ["Baelfyr"] = {["Rank"] = 67,["Kills"] = 1},
            ["Tethis"] = {["Rank"] = 68,["Kills"] = 1},
            ["Stromgarde Cavalryman"] = {["Rank"] = 69,["Kills"] = 1},
            ["Longtooth Runner"] = {["Rank"] = 70,["Kills"] = 1},
            ["Mirefin Puddlejumper"] = {["Rank"] = 71,["Kills"] = 1},
            ["Den Grunt"] = {["Rank"] = 72,["Kills"] = 1},
            ["Lost One Hunter"] = {["Rank"] = 73,["Kills"] = 1},
            ["Maraudine Bonepaw"] = {["Rank"] = 74,["Kills"] = 1},
            ["Sellick Voss"] = {["Rank"] = 75,["Kills"] = 1},
            ["Jailor Borhuin"] = {["Rank"] = 76,["Kills"] = 1},
            ["Kurzen Commando"] = {["Rank"] = 77,["Kills"] = 1},
            ["Skullsplitter Panther"] = {["Rank"] = 78,["Kills"] = 1},
            ["Drywallow Snapper"] = {["Rank"] = 79,["Kills"] = 1},
            ["Zanzil Naga"] = {["Rank"] = 80,["Kills"] = 1},
            ["Outcast Necromancer"] = {["Rank"] = 81,["Kills"] = 1},
            ["Herod"] = {["Rank"] = 82,["Kills"] = 1},
            ["Bloodscalp Hunter"] = {["Rank"] = 83,["Kills"] = 1},
            ["Otto"] = {["Rank"] = 84,["Kills"] = 1},
            ["Blackhorn Warrior"] = {["Rank"] = 85,["Kills"] = 1},
            ["Bloodsail Warlock"] = {["Rank"] = 86,["Kills"] = 1},
            ["Razorfen Battleguard"] = {["Rank"] = 87,["Kills"] = 1},
            ["Maraudine Scout"] = {["Rank"] = 88,["Kills"] = 1},
            ["Bhag'thera"] = {["Rank"] = 89,["Kills"] = 1},
            ["Maraudine Windchaser"] = {["Rank"] = 90,["Kills"] = 1},
            ["Unseen"] = {["Rank"] = 91,["Kills"] = 1},
            ["Boulderfist Enforcer"] = {["Rank"] = 92,["Kills"] = 1},
            ["Green Wyrmkin"] = {["Rank"] = 93,["Kills"] = 1},
            ["Carrion Horror"] = {["Rank"] = 94,["Kills"] = 1},
            ["Aged Kodo"] = {["Rank"] = 95,["Kills"] = 1},
            ["Defias Rioter"] = {["Rank"] = 96,["Kills"] = 1},
            ["King Bangalash"] = {["Rank"] = 97,["Kills"] = 1},
            ["Marsh Inkspewer"] = {["Rank"] = 98,["Kills"] = 1},
            ["Gordunni Brute"] = {["Rank"] = 99,["Kills"] = 1},
            ["Gordunni Mauler"] = {["Rank"] = 100,["Kills"] = 1},
        }
    end
end

function HCRank_players()
    return {
        ["Valkar"] = {["Rank"] = 1,["Kills"] = 136},
        ["Fleshbeard"] = {["Rank"] = 2,["Kills"] = 45},
        ["Greengnom"] = {["Rank"] = 3,["Kills"] = 35},
        ["Zdraxus"] = {["Rank"] = 4,["Kills"] = 29},
        ["Lilrat"] = {["Rank"] = 5,["Kills"] = 14},
        ["Gevilgaz"] = {["Rank"] = 6,["Kills"] = 11},
        ["Slimshadowy"] = {["Rank"] = 7,["Kills"] = 11},
        ["Necrobeard"] = {["Rank"] = 8,["Kills"] = 11},
        ["Bamboozler"] = {["Rank"] = 9,["Kills"] = 10},
        ["Grimus"] = {["Rank"] = 10,["Kills"] = 9},
        ["Chrisophia"] = {["Rank"] = 11,["Kills"] = 8},
        ["Dimkosyan"] = {["Rank"] = 12,["Kills"] = 8},
        ["Shadist"] = {["Rank"] = 13,["Kills"] = 8},
        ["Evolvz"] = {["Rank"] = 14,["Kills"] = 7},
        ["Deaddy"] = {["Rank"] = 15,["Kills"] = 6},
        ["Zaradur"] = {["Rank"] = 16,["Kills"] = 6},
        ["Glin"] = {["Rank"] = 17,["Kills"] = 6},
        ["Stabby"] = {["Rank"] = 18,["Kills"] = 6},
        ["Ripbozohaha"] = {["Rank"] = 19,["Kills"] = 5},
        ["Doob"] = {["Rank"] = 20,["Kills"] = 5},
        ["Mangomazestv"] = {["Rank"] = 21,["Kills"] = 5},
        ["Jimmycarrey"] = {["Rank"] = 22,["Kills"] = 5},
        ["Yosemitesam"] = {["Rank"] = 23,["Kills"] = 5},
        ["Hordeath"] = {["Rank"] = 24,["Kills"] = 5},
        ["Yourmotherr"] = {["Rank"] = 25,["Kills"] = 4},
        ["Minces"] = {["Rank"] = 26,["Kills"] = 4},
        ["Nanachi"] = {["Rank"] = 27,["Kills"] = 4},
        ["Proy"] = {["Rank"] = 28,["Kills"] = 4},
        ["Grovestalker"] = {["Rank"] = 29,["Kills"] = 4},
        ["Eemodru"] = {["Rank"] = 30,["Kills"] = 4},
        ["Pekora"] = {["Rank"] = 31,["Kills"] = 4},
        ["Turzog"] = {["Rank"] = 32,["Kills"] = 4},
        ["Windtop"] = {["Rank"] = 33,["Kills"] = 4},
        ["Zilberman"] = {["Rank"] = 34,["Kills"] = 4},
        ["Dreadblade"] = {["Rank"] = 35,["Kills"] = 4},
        ["Ysomad"] = {["Rank"] = 36,["Kills"] = 4},
        ["Tuve"] = {["Rank"] = 37,["Kills"] = 4},
        ["Nytclaw"] = {["Rank"] = 38,["Kills"] = 4},
        ["Nestro"] = {["Rank"] = 39,["Kills"] = 3},
        ["Grimbatuul"] = {["Rank"] = 40,["Kills"] = 3},
        ["Megalomaniac"] = {["Rank"] = 41,["Kills"] = 3},
        ["Mossadagent"] = {["Rank"] = 42,["Kills"] = 3},
        ["Rhazhai"] = {["Rank"] = 43,["Kills"] = 3},
        ["Elkrinia"] = {["Rank"] = 44,["Kills"] = 3},
        ["Greenpepe"] = {["Rank"] = 45,["Kills"] = 3},
        ["Grizzlie"] = {["Rank"] = 46,["Kills"] = 3},
        ["Shacklez"] = {["Rank"] = 47,["Kills"] = 3},
        ["Abwxo"] = {["Rank"] = 48,["Kills"] = 3},
        ["Wickedjaw"] = {["Rank"] = 49,["Kills"] = 3},
        ["Tipsniffer"] = {["Rank"] = 50,["Kills"] = 3},
        ["Liviid"] = {["Rank"] = 51,["Kills"] = 3},
        ["Exukor"] = {["Rank"] = 52,["Kills"] = 3},
        ["Nyatka"] = {["Rank"] = 53,["Kills"] = 3},
        ["Sammara"] = {["Rank"] = 54,["Kills"] = 2},
        ["Haavoc"] = {["Rank"] = 55,["Kills"] = 2},
        ["Gungner"] = {["Rank"] = 56,["Kills"] = 2},
        ["Bloats"] = {["Rank"] = 57,["Kills"] = 2},
        ["Olinson"] = {["Rank"] = 58,["Kills"] = 2},
        ["Shortstab"] = {["Rank"] = 59,["Kills"] = 2},
        ["Lichking"] = {["Rank"] = 60,["Kills"] = 2},
        ["Zaas"] = {["Rank"] = 61,["Kills"] = 2},
        ["Akmetlt"] = {["Rank"] = 62,["Kills"] = 2},
        ["Chicagobulls"] = {["Rank"] = 63,["Kills"] = 2},
        ["Bootiebandit"] = {["Rank"] = 64,["Kills"] = 2},
        ["Arkimonday"] = {["Rank"] = 65,["Kills"] = 2},
        ["Bytheway"] = {["Rank"] = 66,["Kills"] = 2},
        ["Forskintaker"] = {["Rank"] = 67,["Kills"] = 2},
        ["Jazzpolice"] = {["Rank"] = 68,["Kills"] = 2},
        ["Massorcist"] = {["Rank"] = 69,["Kills"] = 2},
        ["Orcisassault"] = {["Rank"] = 70,["Kills"] = 2},
        ["Jahh"] = {["Rank"] = 71,["Kills"] = 2},
        ["Med"] = {["Rank"] = 72,["Kills"] = 2},
        ["Snaiper"] = {["Rank"] = 73,["Kills"] = 2},
        ["Petrichor"] = {["Rank"] = 74,["Kills"] = 2},
        ["Jabun"] = {["Rank"] = 75,["Kills"] = 2},
        ["Papajohnsceo"] = {["Rank"] = 76,["Kills"] = 2},
        ["Bigginz"] = {["Rank"] = 77,["Kills"] = 2},
        ["Acefisherr"] = {["Rank"] = 78,["Kills"] = 2},
        ["Zarken"] = {["Rank"] = 79,["Kills"] = 2},
        ["Seleucus"] = {["Rank"] = 80,["Kills"] = 2},
        ["Gudreang"] = {["Rank"] = 81,["Kills"] = 2},
        ["Tfs"] = {["Rank"] = 82,["Kills"] = 2},
        ["Whush"] = {["Rank"] = 83,["Kills"] = 2},
        ["Zerodos"] = {["Rank"] = 84,["Kills"] = 2},
        ["Column"] = {["Rank"] = 85,["Kills"] = 2},
        ["Caryww"] = {["Rank"] = 86,["Kills"] = 2},
        ["Warmodekilla"] = {["Rank"] = 87,["Kills"] = 2},
        ["Zorth"] = {["Rank"] = 88,["Kills"] = 2},
        ["Watame"] = {["Rank"] = 89,["Kills"] = 2},
        ["Kultirashero"] = {["Rank"] = 90,["Kills"] = 2},
        ["Kekwaiterz"] = {["Rank"] = 91,["Kills"] = 2},
        ["Evilscum"] = {["Rank"] = 92,["Kills"] = 2},
        ["Kyon"] = {["Rank"] = 93,["Kills"] = 2},
        ["Kuttekop"] = {["Rank"] = 94,["Kills"] = 2},
        ["Barlosmith"] = {["Rank"] = 95,["Kills"] = 2},
        ["Isfet"] = {["Rank"] = 96,["Kills"] = 2},
        ["Freemountain"] = {["Rank"] = 97,["Kills"] = 2},
        ["Naithan"] = {["Rank"] = 98,["Kills"] = 2},
        ["Williamhmacy"] = {["Rank"] = 99,["Kills"] = 2},
        ["Yeszaddy"] = {["Rank"] = 100,["Kills"] = 2},
    }
end