function HCRank_mobs(level)
    if level <= 20 then
        return {
            ["Defias Bodyguard"] = {["Rank"] = 1,["Kills"] = 1831},
            ["Defias Highwayman"] = {["Rank"] = 2,["Kills"] = 1757},
            ["Defias Trapper"] = {["Rank"] = 3,["Kills"] = 1455},
            ["Rockjaw Bonesnapper"] = {["Rank"] = 4,["Kills"] = 832},
            ["Longsnout"] = {["Rank"] = 5,["Kills"] = 657},
            ["Benny Blaanco"] = {["Rank"] = 6,["Kills"] = 563},
            ["Vagash"] = {["Rank"] = 7,["Kills"] = 558},
            ["Riverpaw Bandit"] = {["Rank"] = 8,["Kills"] = 555},
            ["Defias Pillager"] = {["Rank"] = 9,["Kills"] = 554},
            ["Lunaclaw"] = {["Rank"] = 10,["Kills"] = 548},
            ["Burning Blade Toxicologist"] = {["Rank"] = 11,["Kills"] = 542},
            ["Rotting Ancestor"] = {["Rank"] = 12,["Kills"] = 540},
            ["Defias Looter"] = {["Rank"] = 13,["Kills"] = 536},
            ["Riverpaw Outrunner"] = {["Rank"] = 14,["Kills"] = 532},
            ["Burning Blade Apprentice"] = {["Rank"] = 15,["Kills"] = 521},
            ["Warlord Krom'zar"] = {["Rank"] = 16,["Kills"] = 512},
            ["Voidwalker"] = {["Rank"] = 17,["Kills"] = 503},
            ["Sunscale Scytheclaw"] = {["Rank"] = 18,["Kills"] = 503},
            ["Murloc Tidehunter"] = {["Rank"] = 19,["Kills"] = 499},
            ["Tunnel Rat Geomancer"] = {["Rank"] = 20,["Kills"] = 489},
            ["Carver Molsen"] = {["Rank"] = 21,["Kills"] = 488},
            ["Son of Arugal"] = {["Rank"] = 22,["Kills"] = 451},
            ["Stormscale Wave Rider"] = {["Rank"] = 23,["Kills"] = 426},
            ["Witchwing Slayer"] = {["Rank"] = 24,["Kills"] = 414},
            ["Razormane Defender"] = {["Rank"] = 25,["Kills"] = 403},
            ["Tunnel Rat Kobold"] = {["Rank"] = 26,["Kills"] = 395},
            ["Ol' Sooty"] = {["Rank"] = 27,["Kills"] = 395},
            ["Stonesplinter Skullthumper"] = {["Rank"] = 28,["Kills"] = 392},
            ["Harvest Watcher"] = {["Rank"] = 29,["Kills"] = 387},
            ["Venture Co. Enforcer"] = {["Rank"] = 30,["Kills"] = 386},
            ["Dreadmaw Crocolisk"] = {["Rank"] = 31,["Kills"] = 363},
            ["Defias Smuggler"] = {["Rank"] = 32,["Kills"] = 355},
            ["Riverpaw Brute"] = {["Rank"] = 33,["Kills"] = 354},
            ["Kolkar Invader"] = {["Rank"] = 34,["Kills"] = 348},
            ["Fizzle Darkstorm"] = {["Rank"] = 35,["Kills"] = 334},
            ["Stonesplinter Seer"] = {["Rank"] = 36,["Kills"] = 319},
            ["Stonesplinter Trogg"] = {["Rank"] = 37,["Kills"] = 315},
            ["Tunnel Rat Forager"] = {["Rank"] = 38,["Kills"] = 309},
            ["Blackrock Outrunner"] = {["Rank"] = 39,["Kills"] = 308},
            ["Tunnel Rat Digger"] = {["Rank"] = 40,["Kills"] = 296},
            ["Murloc Coastrunner"] = {["Rank"] = 41,["Kills"] = 282},
            ["Theramore Marine"] = {["Rank"] = 42,["Kills"] = 282},
            ["Defias Knuckleduster"] = {["Rank"] = 43,["Kills"] = 281},
            ["Hecklefang Hyena"] = {["Rank"] = 44,["Kills"] = 278},
            ["Kodo Matriarch"] = {["Rank"] = 45,["Kills"] = 264},
            ["Venture Co. Overseer"] = {["Rank"] = 46,["Kills"] = 258},
            ["Gnarlpine Defender"] = {["Rank"] = 47,["Kills"] = 257},
            ["Defias Pathstalker"] = {["Rank"] = 48,["Kills"] = 257},
            ["Gnarlpine Shaman"] = {["Rank"] = 49,["Kills"] = 255},
            ["Stonesplinter Bonesnapper"] = {["Rank"] = 50,["Kills"] = 253},
            ["Dire Condor"] = {["Rank"] = 51,["Kills"] = 248},
            ["Lillith Nefara"] = {["Rank"] = 52,["Kills"] = 246},
            ["Ragefire Trogg"] = {["Rank"] = 53,["Kills"] = 242},
            ["Sand Shark"] = {["Rank"] = 54,["Kills"] = 241},
            ["Bristleback Trapper"] = {["Rank"] = 55,["Kills"] = 234},
            ["Razormane Water Seeker"] = {["Rank"] = 56,["Kills"] = 234},
            ["Deepmoss Matriarch"] = {["Rank"] = 57,["Kills"] = 231},
            ["Raging Moonkin"] = {["Rank"] = 58,["Kills"] = 227},
            ["Murloc Netter"] = {["Rank"] = 59,["Kills"] = 226},
            ["Prowler"] = {["Rank"] = 60,["Kills"] = 212},
            ["Expedition Officer"] = {["Rank"] = 61,["Kills"] = 211},
            ["Defias Bandit"] = {["Rank"] = 62,["Kills"] = 208},
            ["Stormscale Siren"] = {["Rank"] = 63,["Kills"] = 200},
            ["Haren Swifthoof"] = {["Rank"] = 64,["Kills"] = 197},
            ["Gazz'uz"] = {["Rank"] = 65,["Kills"] = 196},
            ["Imp Minion"] = {["Rank"] = 66,["Kills"] = 195},
            ["Thragomm"] = {["Rank"] = 67,["Kills"] = 193},
            ["Gnarlpine Augur"] = {["Rank"] = 68,["Kills"] = 191},
            ["Murloc Oracle"] = {["Rank"] = 69,["Kills"] = 189},
            ["Greymist Coastrunner"] = {["Rank"] = 70,["Kills"] = 186},
            ["Burning Blade Fanatic"] = {["Rank"] = 71,["Kills"] = 185},
            ["Taskmaster Fizzule"] = {["Rank"] = 72,["Kills"] = 185},
            ["Chok'sul"] = {["Rank"] = 73,["Kills"] = 183},
            ["Carnivous the Breaker"] = {["Rank"] = 74,["Kills"] = 181},
            ["Polly"] = {["Rank"] = 75,["Kills"] = 180},
            ["Defias Dockmaster"] = {["Rank"] = 76,["Kills"] = 179},
            ["Stonesplinter Shaman"] = {["Rank"] = 77,["Kills"] = 175},
            ["Gradok"] = {["Rank"] = 78,["Kills"] = 175},
            ["Stonesplinter Scout"] = {["Rank"] = 79,["Kills"] = 173},
            ["Witchwing Roguefeather"] = {["Rank"] = 80,["Kills"] = 172},
            ["Oggleflint"] = {["Rank"] = 81,["Kills"] = 169},
            ["Expedition Commando"] = {["Rank"] = 82,["Kills"] = 168},
            ["Rockjaw Skullthumper"] = {["Rank"] = 83,["Kills"] = 168},
            ["Kolkar Packhound"] = {["Rank"] = 84,["Kills"] = 166},
            ["Southsea Cannoneer"] = {["Rank"] = 85,["Kills"] = 166},
            ["Thistle Bear"] = {["Rank"] = 86,["Kills"] = 163},
            ["Moonrage Darksoul"] = {["Rank"] = 87,["Kills"] = 163},
            ["Riverpaw Miner"] = {["Rank"] = 88,["Kills"] = 160},
            ["Greater Tarantula"] = {["Rank"] = 89,["Kills"] = 159},
            ["Coyote"] = {["Rank"] = 90,["Kills"] = 157},
            ["Ghost Saber"] = {["Rank"] = 91,["Kills"] = 154},
            ["Old Icebeard"] = {["Rank"] = 92,["Kills"] = 153},
            ["Verog the Dervish"] = {["Rank"] = 93,["Kills"] = 152},
            ["Foreman Grills"] = {["Rank"] = 94,["Kills"] = 152},
            ["Thistle Cub"] = {["Rank"] = 95,["Kills"] = 150},
            ["Venture Co. Drudger"] = {["Rank"] = 96,["Kills"] = 149},
            ["Rift Spawn"] = {["Rank"] = 97,["Kills"] = 149},
            ["Riverpaw Mongrel"] = {["Rank"] = 98,["Kills"] = 148},
            ["Foe Reaper 4000"] = {["Rank"] = 99,["Kills"] = 145},
            ["Bristleback Rockshaper"] = {["Rank"] = 100,["Kills"] = 141},
        }
    elseif level <= 30 then
        return {
            ["Deepmoss Matriarch"] = {["Rank"] = 1,["Kills"] = 439},
            ["Stitches"] = {["Rank"] = 2,["Kills"] = 391},
            ["Compact Harvest Reaper"] = {["Rank"] = 3,["Kills"] = 266},
            ["Razormane Stalker"] = {["Rank"] = 4,["Kills"] = 221},
            ["Carver Molsen"] = {["Rank"] = 5,["Kills"] = 175},
            ["Chok'sul"] = {["Rank"] = 6,["Kills"] = 167},
            ["Blackrock Sentry"] = {["Rank"] = 7,["Kills"] = 166},
            ["Shadowhide Slayer"] = {["Rank"] = 8,["Kills"] = 165},
            ["Blackrock Champion"] = {["Rank"] = 9,["Kills"] = 164},
            ["Dark Strand Assassin"] = {["Rank"] = 10,["Kills"] = 155},
            ["Mor'Ladim"] = {["Rank"] = 11,["Kills"] = 151},
            ["Dragonmaw Raider"] = {["Rank"] = 12,["Kills"] = 149},
            ["Silithid Swarm"] = {["Rank"] = 13,["Kills"] = 140},
            ["Hillsbrad Miner"] = {["Rank"] = 14,["Kills"] = 123},
            ["Defias Raider"] = {["Rank"] = 15,["Kills"] = 104},
            ["Skeletal Miner"] = {["Rank"] = 16,["Kills"] = 104},
            ["Bael'dun Officer"] = {["Rank"] = 17,["Kills"] = 103},
            ["Warlord Krom'zar"] = {["Rank"] = 18,["Kills"] = 102},
            ["Blackrock Tracker"] = {["Rank"] = 19,["Kills"] = 102},
            ["Goggeroc"] = {["Rank"] = 20,["Kills"] = 101},
            ["Defias Blackguard"] = {["Rank"] = 21,["Kills"] = 101},
            ["Blackrock Outrunner"] = {["Rank"] = 22,["Kills"] = 99},
            ["Bloodfury Ripper"] = {["Rank"] = 23,["Kills"] = 99},
            ["Dun Garok Soldier"] = {["Rank"] = 24,["Kills"] = 98},
            ["Bael'dun Foreman"] = {["Rank"] = 25,["Kills"] = 95},
            ["Defias Digger"] = {["Rank"] = 26,["Kills"] = 88},
            ["Wildthorn Lurker"] = {["Rank"] = 27,["Kills"] = 87},
            ["Deepmoss Hatchling"] = {["Rank"] = 28,["Kills"] = 86},
            ["Cursed Marine"] = {["Rank"] = 29,["Kills"] = 85},
            ["Wretched Bodyguard"] = {["Rank"] = 30,["Kills"] = 84},
            ["Defias Pirate"] = {["Rank"] = 31,["Kills"] = 83},
            ["Shadowhide Warrior"] = {["Rank"] = 32,["Kills"] = 83},
            ["Nightbane Dark Runner"] = {["Rank"] = 33,["Kills"] = 83},
            ["Devouring Ectoplasm"] = {["Rank"] = 34,["Kills"] = 81},
            ["Flesh Eating Worm"] = {["Rank"] = 35,["Kills"] = 80},
            ["Syndicate Watchman"] = {["Rank"] = 36,["Kills"] = 79},
            ["Horde Guard"] = {["Rank"] = 37,["Kills"] = 78},
            ["Redridge Basher"] = {["Rank"] = 38,["Kills"] = 77},
            ["Defias Highwayman"] = {["Rank"] = 39,["Kills"] = 76},
            ["Shadowhide Brute"] = {["Rank"] = 40,["Kills"] = 76},
            ["Grunt"] = {["Rank"] = 41,["Kills"] = 75},
            ["Blackrock Summoner"] = {["Rank"] = 42,["Kills"] = 75},
            ["Black Widow Hatchling"] = {["Rank"] = 43,["Kills"] = 75},
            ["Cursed Sailor"] = {["Rank"] = 44,["Kills"] = 74},
            ["Aku'mai Snapjaw"] = {["Rank"] = 45,["Kills"] = 73},
            ["Druid of the Fang"] = {["Rank"] = 46,["Kills"] = 72},
            ["Crimson Ooze"] = {["Rank"] = 47,["Kills"] = 71},
            ["Galak Assassin"] = {["Rank"] = 48,["Kills"] = 70},
            ["Blackrock Gladiator"] = {["Rank"] = 49,["Kills"] = 68},
            ["Bloodfury Ambusher"] = {["Rank"] = 50,["Kills"] = 68},
            ["Bael'dun Soldier"] = {["Rank"] = 51,["Kills"] = 67},
            ["Besseleth"] = {["Rank"] = 52,["Kills"] = 66},
            ["Defias Henchman"] = {["Rank"] = 53,["Kills"] = 65},
            ["Bleak Worg"] = {["Rank"] = 54,["Kills"] = 65},
            ["Deviate Creeper"] = {["Rank"] = 55,["Kills"] = 64},
            ["Ol' Sooty"] = {["Rank"] = 56,["Kills"] = 64},
            ["Deepmoss Creeper"] = {["Rank"] = 57,["Kills"] = 63},
            ["Taskmaster Whipfang"] = {["Rank"] = 58,["Kills"] = 62},
            ["Dragonmaw Grunt"] = {["Rank"] = 59,["Kills"] = 62},
            ["Redridge Alpha"] = {["Rank"] = 60,["Kills"] = 62},
            ["Edwin VanCleef"] = {["Rank"] = 61,["Kills"] = 62},
            ["Mosshide Mongrel"] = {["Rank"] = 62,["Kills"] = 61},
            ["Bael'dun Excavator"] = {["Rank"] = 63,["Kills"] = 61},
            ["Silithid Grub"] = {["Rank"] = 64,["Kills"] = 60},
            ["Defias Overseer"] = {["Rank"] = 65,["Kills"] = 59},
            ["Riverpaw Bandit"] = {["Rank"] = 66,["Kills"] = 58},
            ["Lupine Delusion"] = {["Rank"] = 67,["Kills"] = 58},
            ["Venture Co. Enforcer"] = {["Rank"] = 68,["Kills"] = 57},
            ["Wandering Protector"] = {["Rank"] = 69,["Kills"] = 57},
            ["Windshear Digger"] = {["Rank"] = 70,["Kills"] = 57},
            ["Lupine Horror"] = {["Rank"] = 71,["Kills"] = 56},
            ["Defias Inmate"] = {["Rank"] = 72,["Kills"] = 56},
            ["Defias Squallshaper"] = {["Rank"] = 73,["Kills"] = 55},
            ["Barrens Guard"] = {["Rank"] = 74,["Kills"] = 55},
            ["Mosshide Brute"] = {["Rank"] = 75,["Kills"] = 53},
            ["Greymist Coastrunner"] = {["Rank"] = 76,["Kills"] = 52},
            ["Unseen"] = {["Rank"] = 77,["Kills"] = 52},
            ["Blackrock Hunter"] = {["Rank"] = 78,["Kills"] = 52},
            ["Hannah Bladeleaf"] = {["Rank"] = 79,["Kills"] = 51},
            ["Redridge Mystic"] = {["Rank"] = 80,["Kills"] = 51},
            ["Thora Feathermoon"] = {["Rank"] = 81,["Kills"] = 50},
            ["Silithid Protector"] = {["Rank"] = 82,["Kills"] = 50},
            ["Befouled Water Elemental"] = {["Rank"] = 83,["Kills"] = 50},
            ["Mosshide Alpha"] = {["Rank"] = 84,["Kills"] = 50},
            ["Plague Spreader"] = {["Rank"] = 85,["Kills"] = 50},
            ["Hillsbrad Foreman"] = {["Rank"] = 86,["Kills"] = 50},
            ["Taskmaster Fizzule"] = {["Rank"] = 87,["Kills"] = 49},
            ["Marcus Bel"] = {["Rank"] = 88,["Kills"] = 49},
            ["Slavering Worg"] = {["Rank"] = 89,["Kills"] = 49},
            ["Defias Rioter"] = {["Rank"] = 90,["Kills"] = 49},
            ["Nightbane Shadow Weaver"] = {["Rank"] = 91,["Kills"] = 49},
            ["Slim's Friend"] = {["Rank"] = 92,["Kills"] = 48},
            ["Defias Night Runner"] = {["Rank"] = 93,["Kills"] = 47},
            ["Defias Night Blade"] = {["Rank"] = 94,["Kills"] = 46},
            ["Silithid Swarmer"] = {["Rank"] = 95,["Kills"] = 44},
            ["Skeletal Horror"] = {["Rank"] = 96,["Kills"] = 44},
            ["Thule Ravenclaw"] = {["Rank"] = 97,["Kills"] = 44},
            ["Shadowhide Darkweaver"] = {["Rank"] = 98,["Kills"] = 44},
            ["Pesterhide Snarler"] = {["Rank"] = 99,["Kills"] = 44},
            ["Venture Co. Overseer"] = {["Rank"] = 100,["Kills"] = 43},
        }
    elseif level <= 40 then
        return {
            ["Blastmaster Emi Shortfuse"] = {["Rank"] = 1,["Kills"] = 117},
            ["Kurzen Commando"] = {["Rank"] = 2,["Kills"] = 79},
            ["Deranged Ancient"] = {["Rank"] = 3,["Kills"] = 78},
            ["Magrami Spectre"] = {["Rank"] = 4,["Kills"] = 73},
            ["Undead Ravager"] = {["Rank"] = 5,["Kills"] = 67},
            ["Warleader Kintoza"] = {["Rank"] = 6,["Kills"] = 54},
            ["Syndicate Prowler"] = {["Rank"] = 7,["Kills"] = 49},
            ["Dragonmaw Raider"] = {["Rank"] = 8,["Kills"] = 46},
            ["Slim's Friend"] = {["Rank"] = 9,["Kills"] = 46},
            ["Witherbark Headhunter"] = {["Rank"] = 10,["Kills"] = 46},
            ["Syndicate Thief"] = {["Rank"] = 11,["Kills"] = 45},
            ["Eliza's Guard"] = {["Rank"] = 12,["Kills"] = 44},
            ["Grenka Bloodscreech"] = {["Rank"] = 13,["Kills"] = 40},
            ["Dun Garok Mountaineer"] = {["Rank"] = 14,["Kills"] = 39},
            ["Tarren Mill Deathguard"] = {["Rank"] = 15,["Kills"] = 38},
            ["Elder Saltwater Crocolisk"] = {["Rank"] = 16,["Kills"] = 36},
            ["Barrens Guard"] = {["Rank"] = 17,["Kills"] = 35},
            ["Maraudine Bonepaw"] = {["Rank"] = 18,["Kills"] = 35},
            ["Stitches"] = {["Rank"] = 19,["Kills"] = 32},
            ["Darkmist Silkspinner"] = {["Rank"] = 20,["Kills"] = 32},
            ["Scarlet Sentry"] = {["Rank"] = 21,["Kills"] = 31},
            ["Bloodscalp Hunter"] = {["Rank"] = 22,["Kills"] = 31},
            ["Screeching Harpy"] = {["Rank"] = 23,["Kills"] = 30},
            ["Hillsbrad Miner"] = {["Rank"] = 24,["Kills"] = 29},
            ["Unseen"] = {["Rank"] = 25,["Kills"] = 29},
            ["Crushridge Warmonger"] = {["Rank"] = 26,["Kills"] = 29},
            ["Mor'Ladim"] = {["Rank"] = 27,["Kills"] = 28},
            ["Crushridge Mauler"] = {["Rank"] = 28,["Kills"] = 27},
            ["Dun Garok Soldier"] = {["Rank"] = 29,["Kills"] = 26},
            ["Mosh'Ogg Warmonger"] = {["Rank"] = 30,["Kills"] = 26},
            ["Saltscale Warrior"] = {["Rank"] = 31,["Kills"] = 26},
            ["Southshore Guard"] = {["Rank"] = 32,["Kills"] = 25},
            ["Morbent Fel"] = {["Rank"] = 33,["Kills"] = 25},
            ["Burning Blade Felsworn"] = {["Rank"] = 34,["Kills"] = 25},
            ["Scarlet Myrmidon"] = {["Rank"] = 35,["Kills"] = 25},
            ["Hammerfall Peon"] = {["Rank"] = 36,["Kills"] = 24},
            ["Chieftain Nek'rosh"] = {["Rank"] = 37,["Kills"] = 22},
            ["Bloodscalp Scout"] = {["Rank"] = 38,["Kills"] = 22},
            ["Maraudine Wrangler"] = {["Rank"] = 39,["Kills"] = 22},
            ["Syndicate Spy"] = {["Rank"] = 40,["Kills"] = 21},
            ["Saltscale Oracle"] = {["Rank"] = 41,["Kills"] = 21},
            ["Kurzen Subchief"] = {["Rank"] = 42,["Kills"] = 21},
            ["Nightbane Dark Runner"] = {["Rank"] = 43,["Kills"] = 20},
            ["Kolkar Destroyer"] = {["Rank"] = 44,["Kills"] = 20},
            ["Skeletal Raider"] = {["Rank"] = 45,["Kills"] = 20},
            ["Scarlet Monk"] = {["Rank"] = 46,["Kills"] = 20},
            ["Witherbark Rogue"] = {["Rank"] = 47,["Kills"] = 20},
            ["Scorpid Reaver"] = {["Rank"] = 48,["Kills"] = 19},
            ["Mechanized Guardian"] = {["Rank"] = 49,["Kills"] = 19},
            ["Thanthaldis Snowgleam"] = {["Rank"] = 50,["Kills"] = 18},
            ["Kurzen Medicine Man"] = {["Rank"] = 51,["Kills"] = 18},
            ["Old Town Thug"] = {["Rank"] = 52,["Kills"] = 17},
            ["Dark Iron Dwarf"] = {["Rank"] = 53,["Kills"] = 17},
            ["Drywallow Daggermaw"] = {["Rank"] = 54,["Kills"] = 17},
            ["Dark Iron Agent"] = {["Rank"] = 55,["Kills"] = 17},
            ["Bloodscalp Shaman"] = {["Rank"] = 56,["Kills"] = 17},
            ["Blackhorn Mystic"] = {["Rank"] = 57,["Kills"] = 17},
            ["Balgaras the Foul"] = {["Rank"] = 58,["Kills"] = 16},
            ["Dark Iron Tunneler"] = {["Rank"] = 59,["Kills"] = 16},
            ["Mirkfallon Keeper"] = {["Rank"] = 60,["Kills"] = 16},
            ["Scarlet Torturer"] = {["Rank"] = 61,["Kills"] = 15},
            ["Dalaran Shield Guard"] = {["Rank"] = 62,["Kills"] = 15},
            ['Tapoke "Slim" Jahn'] = {["Rank"] = 63,["Kills"] = 15},
            ["Aku'mai Snapjaw"] = {["Rank"] = 64,["Kills"] = 15},
            ["Eliza"] = {["Rank"] = 65,["Kills"] = 15},
            ["Boulderfist Mauler"] = {["Rank"] = 66,["Kills"] = 15},
            ["Scarlet Recruit"] = {["Rank"] = 67,["Kills"] = 15},
            ["Syndicate Wizard"] = {["Rank"] = 68,["Kills"] = 15},
            ["Bloodscalp Mystic"] = {["Rank"] = 69,["Kills"] = 15},
            ["Witherbark Raider"] = {["Rank"] = 70,["Kills"] = 15},
            ["Bhag'thera"] = {["Rank"] = 71,["Kills"] = 15},
            ["Tethis"] = {["Rank"] = 72,["Kills"] = 15},
            ["Dark Iron Demolitionist"] = {["Rank"] = 73,["Kills"] = 14},
            ["Plague Spreader"] = {["Rank"] = 74,["Kills"] = 14},
            ["Quilguard Champion"] = {["Rank"] = 75,["Kills"] = 14},
            ["Bloodsail Raider"] = {["Rank"] = 76,["Kills"] = 14},
            ["Roaming Felguard"] = {["Rank"] = 77,["Kills"] = 14},
            ["Stromgarde Cavalryman"] = {["Rank"] = 78,["Kills"] = 13},
            ["Hillsbrad Foreman"] = {["Rank"] = 79,["Kills"] = 13},
            ["Holdout Warrior"] = {["Rank"] = 80,["Kills"] = 13},
            ["Kurzen Jungle Fighter"] = {["Rank"] = 81,["Kills"] = 13},
            ["Firemane Ash Tail"] = {["Rank"] = 82,["Kills"] = 13},
            ["Baelfyr"] = {["Rank"] = 83,["Kills"] = 13},
            ["Bloodsail Mage"] = {["Rank"] = 84,["Kills"] = 13},
            ["Galak Assassin"] = {["Rank"] = 85,["Kills"] = 12},
            ["Skeleton"] = {["Rank"] = 86,["Kills"] = 12},
            ["Vile Sting"] = {["Rank"] = 87,["Kills"] = 12},
            ["Freewind Brave"] = {["Rank"] = 88,["Kills"] = 12},
            ["Witherbark Shadow Hunter"] = {["Rank"] = 89,["Kills"] = 12},
            ["Colonel Kurzen"] = {["Rank"] = 90,["Kills"] = 12},
            ["Blackhorn Warrior"] = {["Rank"] = 91,["Kills"] = 12},
            ["Highland Thrasher"] = {["Rank"] = 92,["Kills"] = 11},
            ["Razorfen Servitor"] = {["Rank"] = 93,["Kills"] = 11},
            ["Salt Flats Scavenger"] = {["Rank"] = 94,["Kills"] = 11},
            ["Mechanized Sentry"] = {["Rank"] = 95,["Kills"] = 11},
            ["Kurzen Wrangler"] = {["Rank"] = 96,["Kills"] = 11},
            ["Bloodscalp Berserker"] = {["Rank"] = 97,["Kills"] = 11},
            ["Mirefin Puddlejumper"] = {["Rank"] = 98,["Kills"] = 11},
            ["Thenan"] = {["Rank"] = 99,["Kills"] = 11},
            ["Outcast Necromancer"] = {["Rank"] = 100,["Kills"] = 11},
        }
    elseif level <= 59 then
        return {
            ["Fleet Master Firallon"] = {["Rank"] = 1,["Kills"] = 43},
            ["Firemane Ash Tail"] = {["Rank"] = 2,["Kills"] = 29},
            ["Grol the Destroyer"] = {["Rank"] = 3,["Kills"] = 29},
            ["Vilebranch Kidnapper"] = {["Rank"] = 4,["Kills"] = 28},
            ["Zul'Farrak Zombie"] = {["Rank"] = 5,["Kills"] = 28},
            ["Firemane Scout"] = {["Rank"] = 6,["Kills"] = 27},
            ["Maraudine Bonepaw"] = {["Rank"] = 7,["Kills"] = 24},
            ["Jaedenar Adept"] = {["Rank"] = 8,["Kills"] = 24},
            ["Farmer Dalson"] = {["Rank"] = 9,["Kills"] = 24},
            ["Magrami Spectre"] = {["Rank"] = 10,["Kills"] = 23},
            ["Gorishi Hive Guard"] = {["Rank"] = 11,["Kills"] = 23},
            ["Bloodsail Sea Dog"] = {["Rank"] = 12,["Kills"] = 21},
            ["Shadowforge Digger"] = {["Rank"] = 13,["Kills"] = 21},
            ["Bloodsail Elder Magus"] = {["Rank"] = 14,["Kills"] = 20},
            ["Khan Hratha"] = {["Rank"] = 15,["Kills"] = 18},
            ["Bloodsail Deckhand"] = {["Rank"] = 16,["Kills"] = 18},
            ["Wastewander Assassin"] = {["Rank"] = 17,["Kills"] = 18},
            ["Hatecrest Serpent Guard"] = {["Rank"] = 18,["Kills"] = 18},
            ["Zetharia"] = {["Rank"] = 19,["Kills"] = 17},
            ["Vilebranch Raiding Wolf"] = {["Rank"] = 20,["Kills"] = 16},
            ["King Mosh"] = {["Rank"] = 21,["Kills"] = 16},
            ["Faladar Starsplinter"] = {["Rank"] = 22,["Kills"] = 15},
            ["Fallen Hero"] = {["Rank"] = 23,["Kills"] = 15},
            ["Maraudine Wrangler"] = {["Rank"] = 24,["Kills"] = 14},
            ["Bloodsail Mage"] = {["Rank"] = 25,["Kills"] = 14},
            ["Somnus"] = {["Rank"] = 26,["Kills"] = 14},
            ["Mai'Zoth"] = {["Rank"] = 27,["Kills"] = 14},
            ["Garr Salthoof"] = {["Rank"] = 28,["Kills"] = 14},
            ["Witherbark Felhunter"] = {["Rank"] = 29,["Kills"] = 14},
            ["Shadowforge Wyrm Hunter"] = {["Rank"] = 30,["Kills"] = 13},
            ["Vilebranch Aman'zasi Guard"] = {["Rank"] = 31,["Kills"] = 13},
            ["Jaedenar Cultist"] = {["Rank"] = 32,["Kills"] = 13},
            ["King Bangalash"] = {["Rank"] = 33,["Kills"] = 12},
            ["Enraged Silverback Gorilla"] = {["Rank"] = 34,["Kills"] = 11},
            ["Crushridge Warmonger"] = {["Rank"] = 35,["Kills"] = 11},
            ["Mosh'Ogg Warmonger"] = {["Rank"] = 36,["Kills"] = 11},
            ["Baelfyr"] = {["Rank"] = 37,["Kills"] = 10},
            ["Bloodsail Warlock"] = {["Rank"] = 38,["Kills"] = 10},
            ["Konda"] = {["Rank"] = 39,["Kills"] = 10},
            ["Zanzil Naga"] = {["Rank"] = 40,["Kills"] = 10},
            ["Undead Ravager"] = {["Rank"] = 41,["Kills"] = 10},
            ["Stonard Grunt"] = {["Rank"] = 42,["Kills"] = 10},
            ["Darkmist Lurker"] = {["Rank"] = 43,["Kills"] = 10},
            ["Scorpid Duneburrower"] = {["Rank"] = 44,["Kills"] = 10},
            ["Booty Bay Bruiser"] = {["Rank"] = 45,["Kills"] = 10},
            ["Hazzali Parasite"] = {["Rank"] = 46,["Kills"] = 10},
            ["Tyrant Devilsaur"] = {["Rank"] = 47,["Kills"] = 10},
            ["Drywallow Daggermaw"] = {["Rank"] = 48,["Kills"] = 9},
            ["Enraged Rock Elemental"] = {["Rank"] = 49,["Kills"] = 9},
            ["Daggerspine Raider"] = {["Rank"] = 50,["Kills"] = 9},
            ["Dark Iron Slaver"] = {["Rank"] = 51,["Kills"] = 9},
            ["Scarlet Invoker"] = {["Rank"] = 52,["Kills"] = 9},
            ["Hive'Ashi Drone"] = {["Rank"] = 53,["Kills"] = 9},
            ["Shadowforge Warrior"] = {["Rank"] = 54,["Kills"] = 8},
            ["Maraudine Khan Guard"] = {["Rank"] = 55,["Kills"] = 8},
            ["Scarlet Myrmidon"] = {["Rank"] = 56,["Kills"] = 8},
            ["Colonel Kurzen"] = {["Rank"] = 57,["Kills"] = 8},
            ["Kurzen Subchief"] = {["Rank"] = 58,["Kills"] = 8},
            ["Vault Warder"] = {["Rank"] = 59,["Kills"] = 8},
            ["Wastewander Shadow Mage"] = {["Rank"] = 60,["Kills"] = 8},
            ["Crimson Elite"] = {["Rank"] = 61,["Kills"] = 8},
            ["Bloodsail Raider"] = {["Rank"] = 62,["Kills"] = 7},
            ["Herod"] = {["Rank"] = 63,["Kills"] = 7},
            ["Searing Whelp"] = {["Rank"] = 64,["Kills"] = 7},
            ["Daggerspine Sorceress"] = {["Rank"] = 65,["Kills"] = 7},
            ["Shadowforge Ruffian"] = {["Rank"] = 66,["Kills"] = 7},
            ["Shadowforge Trapper"] = {["Rank"] = 67,["Kills"] = 7},
            ["Gordunni Brute"] = {["Rank"] = 68,["Kills"] = 7},
            ["Scalebane Captain"] = {["Rank"] = 69,["Kills"] = 7},
            ["Southsea Freebooter"] = {["Rank"] = 70,["Kills"] = 7},
            ["Scorpid Hunter"] = {["Rank"] = 71,["Kills"] = 7},
            ["Centipaar Tunneler"] = {["Rank"] = 72,["Kills"] = 7},
            ["Cliff Walker"] = {["Rank"] = 73,["Kills"] = 7},
            ["Xalvic Blackclaw"] = {["Rank"] = 74,["Kills"] = 7},
            ["The Cleaner"] = {["Rank"] = 75,["Kills"] = 7},
            ["Deranged Ancient"] = {["Rank"] = 76,["Kills"] = 6},
            ["Mirefin Puddlejumper"] = {["Rank"] = 77,["Kills"] = 6},
            ["Tethis"] = {["Rank"] = 78,["Kills"] = 6},
            ["Searing Ghoul"] = {["Rank"] = 79,["Kills"] = 6},
            ["Silvermane Stalker"] = {["Rank"] = 80,["Kills"] = 6},
            ["Camp Mojache Brave"] = {["Rank"] = 81,["Kills"] = 6},
            ["Rumbler"] = {["Rank"] = 82,["Kills"] = 6},
            ["Grimtotem Raider"] = {["Rank"] = 83,["Kills"] = 6},
            ["Mosh'Ogg Spellcrafter"] = {["Rank"] = 84,["Kills"] = 6},
            ["Southsea Swashbuckler"] = {["Rank"] = 85,["Kills"] = 6},
            ["Grimtotem Shaman"] = {["Rank"] = 86,["Kills"] = 6},
            ["Retherokk the Berserker"] = {["Rank"] = 87,["Kills"] = 6},
            ["Dark Iron Steelshifter"] = {["Rank"] = 88,["Kills"] = 6},
            ["Un'Goro Thunderer"] = {["Rank"] = 89,["Kills"] = 6},
            ["Slavering Ghoul"] = {["Rank"] = 90,["Kills"] = 6},
            ["Crimson Courier"] = {["Rank"] = 91,["Kills"] = 6},
            ["Hazzuri Darkcaller"] = {["Rank"] = 92,["Kills"] = 6},
            ["Crimson Bodyguard"] = {["Rank"] = 93,["Kills"] = 6},
            ["Starving Blisterpaw"] = {["Rank"] = 94,["Kills"] = 5},
            ["Skullsplitter Panther"] = {["Rank"] = 95,["Kills"] = 5},
            ["Syndicate Prowler"] = {["Rank"] = 96,["Kills"] = 5},
            ["Scalding Whelp"] = {["Rank"] = 97,["Kills"] = 5},
            ["Ambassador Infernus"] = {["Rank"] = 98,["Kills"] = 5},
            ["Green Wyrmkin"] = {["Rank"] = 99,["Kills"] = 5},
            ["Kegdesh Foulmantle"] = {["Rank"] = 100,["Kills"] = 5},
        }
    end
end

function HCRank_players()
    return {
        ["Valkar"] = {["Rank"] = 1,["Kills"] = 168},
        ["Zdraxus"] = {["Rank"] = 2,["Kills"] = 96},
        ["Fleshbeard"] = {["Rank"] = 3,["Kills"] = 62},
        ["Gordunni"] = {["Rank"] = 4,["Kills"] = 53},
        ["Greengnom"] = {["Rank"] = 5,["Kills"] = 35},
        ["Massive"] = {["Rank"] = 6,["Kills"] = 24},
        ["Nytclaw"] = {["Rank"] = 7,["Kills"] = 24},
        ["Zebraninnu"] = {["Rank"] = 8,["Kills"] = 23},
        ["Necrobeard"] = {["Rank"] = 9,["Kills"] = 21},
        ["Canals"] = {["Rank"] = 10,["Kills"] = 20},
        ["Kekboy"] = {["Rank"] = 11,["Kills"] = 20},
        ["Grimbatuul"] = {["Rank"] = 12,["Kills"] = 20},
        ["Glin"] = {["Rank"] = 13,["Kills"] = 19},
        ["Grimus"] = {["Rank"] = 14,["Kills"] = 18},
        ["Corvan"] = {["Rank"] = 15,["Kills"] = 17},
        ["Gevilgaz"] = {["Rank"] = 16,["Kills"] = 16},
        ["Redridgeboss"] = {["Rank"] = 17,["Kills"] = 15},
        ["Fargus"] = {["Rank"] = 18,["Kills"] = 14},
        ["Keepingfit"] = {["Rank"] = 19,["Kills"] = 14},
        ["Lilrat"] = {["Rank"] = 20,["Kills"] = 14},
        ["Drowner"] = {["Rank"] = 21,["Kills"] = 13},
        ["Dimkosyan"] = {["Rank"] = 22,["Kills"] = 13},
        ["Shmuckzo"] = {["Rank"] = 23,["Kills"] = 12},
        ["Bamboozler"] = {["Rank"] = 24,["Kills"] = 12},
        ["Slimshadowy"] = {["Rank"] = 25,["Kills"] = 11},
        ["Bye"] = {["Rank"] = 26,["Kills"] = 11},
        ["Gankmanager"] = {["Rank"] = 27,["Kills"] = 10},
        ["Pvpgodgamerx"] = {["Rank"] = 28,["Kills"] = 10},
        ["Dreadblade"] = {["Rank"] = 29,["Kills"] = 10},
        ["Chrisophia"] = {["Rank"] = 30,["Kills"] = 10},
        ["Tarkus"] = {["Rank"] = 31,["Kills"] = 10},
        ["Dnu"] = {["Rank"] = 32,["Kills"] = 10},
        ["Itistheend"] = {["Rank"] = 33,["Kills"] = 9},
        ["Zarken"] = {["Rank"] = 34,["Kills"] = 9},
        ["Biz"] = {["Rank"] = 35,["Kills"] = 9},
        ["Coldjoojoo"] = {["Rank"] = 36,["Kills"] = 9},
        ["Tuve"] = {["Rank"] = 37,["Kills"] = 9},
        ["Shadist"] = {["Rank"] = 38,["Kills"] = 9},
        ["Doob"] = {["Rank"] = 39,["Kills"] = 8},
        ["Lichking"] = {["Rank"] = 40,["Kills"] = 8},
        ["Lijwa"] = {["Rank"] = 41,["Kills"] = 8},
        ["Golgorg"] = {["Rank"] = 42,["Kills"] = 8},
        ["Unclescam"] = {["Rank"] = 43,["Kills"] = 8},
        ["Jezzebel"] = {["Rank"] = 44,["Kills"] = 8},
        ["Stabby"] = {["Rank"] = 45,["Kills"] = 8},
        ["Friendhelper"] = {["Rank"] = 46,["Kills"] = 8},
        ["Turzog"] = {["Rank"] = 47,["Kills"] = 8},
        ["Goblintoes"] = {["Rank"] = 48,["Kills"] = 8},
        ["Spiderbait"] = {["Rank"] = 49,["Kills"] = 8},
        ["Deaddy"] = {["Rank"] = 50,["Kills"] = 8},
        ["Vkusno"] = {["Rank"] = 51,["Kills"] = 8},
        ["Josalex"] = {["Rank"] = 52,["Kills"] = 8},
        ["Wickedjaw"] = {["Rank"] = 53,["Kills"] = 8},
        ["Megalomaniac"] = {["Rank"] = 54,["Kills"] = 7},
        ["Sugarwin"] = {["Rank"] = 55,["Kills"] = 7},
        ["Evolvz"] = {["Rank"] = 56,["Kills"] = 7},
        ["Murn"] = {["Rank"] = 57,["Kills"] = 7},
        ["Warmode"] = {["Rank"] = 58,["Kills"] = 7},
        ["Hettaku"] = {["Rank"] = 59,["Kills"] = 7},
        ["Zaradur"] = {["Rank"] = 60,["Kills"] = 6},
        ["Proy"] = {["Rank"] = 61,["Kills"] = 6},
        ["Foxdie"] = {["Rank"] = 62,["Kills"] = 6},
        ["Grovestalker"] = {["Rank"] = 63,["Kills"] = 6},
        ["Bunkerfaust"] = {["Rank"] = 64,["Kills"] = 6},
        ["Defiaspesant"] = {["Rank"] = 65,["Kills"] = 6},
        ["Liangchaowei"] = {["Rank"] = 66,["Kills"] = 6},
        ["Elkrinia"] = {["Rank"] = 67,["Kills"] = 6},
        ["Minces"] = {["Rank"] = 68,["Kills"] = 6},
        ["Cooper"] = {["Rank"] = 69,["Kills"] = 6},
        ["Muurph"] = {["Rank"] = 70,["Kills"] = 6},
        ["Johnnydeath"] = {["Rank"] = 71,["Kills"] = 6},
        ["Ripbozohaha"] = {["Rank"] = 72,["Kills"] = 6},
        ["Nanachi"] = {["Rank"] = 73,["Kills"] = 6},
        ["Arium"] = {["Rank"] = 74,["Kills"] = 6},
        ["Cvnt"] = {["Rank"] = 75,["Kills"] = 6},
        ["Yourmotherr"] = {["Rank"] = 76,["Kills"] = 5},
        ["Nowpay"] = {["Rank"] = 77,["Kills"] = 5},
        ["Naithan"] = {["Rank"] = 78,["Kills"] = 5},
        ["Mangomazestv"] = {["Rank"] = 79,["Kills"] = 5},
        ["Jimmycarrey"] = {["Rank"] = 80,["Kills"] = 5},
        ["Magisterchim"] = {["Rank"] = 81,["Kills"] = 5},
        ["Benidikt"] = {["Rank"] = 82,["Kills"] = 5},
        ["Jabun"] = {["Rank"] = 83,["Kills"] = 5},
        ["Faralynn"] = {["Rank"] = 84,["Kills"] = 5},
        ["Bonah"] = {["Rank"] = 85,["Kills"] = 5},
        ["Doomhandle"] = {["Rank"] = 86,["Kills"] = 5},
        ["Yosemitesam"] = {["Rank"] = 87,["Kills"] = 5},
        ["Spookerina"] = {["Rank"] = 88,["Kills"] = 5},
        ["Rumgrog"] = {["Rank"] = 89,["Kills"] = 5},
        ["Variss"] = {["Rank"] = 90,["Kills"] = 5},
        ["Hordeath"] = {["Rank"] = 91,["Kills"] = 5},
        ["Windtop"] = {["Rank"] = 92,["Kills"] = 5},
        ["Betabitz"] = {["Rank"] = 93,["Kills"] = 5},
        ["Ghibis"] = {["Rank"] = 94,["Kills"] = 4},
        ["Agilee"] = {["Rank"] = 95,["Kills"] = 4},
        ["Phuqqinrun"] = {["Rank"] = 96,["Kills"] = 4},
        ["Zilberman"] = {["Rank"] = 97,["Kills"] = 4},
        ["Daft"] = {["Rank"] = 98,["Kills"] = 4},
        ["Lathirias"] = {["Rank"] = 99,["Kills"] = 4},
        ["Peter"] = {["Rank"] = 100,["Kills"] = 4},
    }
end