
function MobRank.Data()
    MobRank.mobs_1020 = {
        ["Defias Bodyguard"] = {["Rank"] = 1,["Kills"] = 242},
        ["Defias Highwayman"] = {["Rank"] = 2,["Kills"] = 166},
        ["Defias Trapper"] = {["Rank"] = 3,["Kills"] = 151},
        ["Rockjaw Bonesnapper"] = {["Rank"] = 4,["Kills"] = 122},
        ["Tunnel Rat Geomancer"] = {["Rank"] = 5,["Kills"] = 99},
        ["Vagash"] = {["Rank"] = 6,["Kills"] = 86},
        ["Sunscale Scytheclaw"] = {["Rank"] = 7,["Kills"] = 77},
        ["Rotting Ancestor"] = {["Rank"] = 8,["Kills"] = 71},
        ["Voidwalker"] = {["Rank"] = 9,["Kills"] = 69},
        ["Lunaclaw"] = {["Rank"] = 10,["Kills"] = 68},
        ["Defias Pillager"] = {["Rank"] = 11,["Kills"] = 64},
        ["Burning Blade Apprentice"] = {["Rank"] = 12,["Kills"] = 60},
        ["Carver Molsen"] = {["Rank"] = 13,["Kills"] = 60},
        ["Bristleback Trapper"] = {["Rank"] = 14,["Kills"] = 59},
        ["Fizzle Darkstorm"] = {["Rank"] = 15,["Kills"] = 58},
        ["Razormane Defender"] = {["Rank"] = 16,["Kills"] = 57},
        ["Defias Looter"] = {["Rank"] = 17,["Kills"] = 56},
        ["Warlord Krom'zar"] = {["Rank"] = 18,["Kills"] = 56},
        ["Son of Arugal"] = {["Rank"] = 19,["Kills"] = 55},
        ["Benny Blaanco"] = {["Rank"] = 20,["Kills"] = 53},
        ["Tunnel Rat Kobold"] = {["Rank"] = 21,["Kills"] = 53},
        ["Riverpaw Outrunner"] = {["Rank"] = 22,["Kills"] = 52},
        ["Burning Blade Toxicologist"] = {["Rank"] = 23,["Kills"] = 51},
        ["Longsnout"] = {["Rank"] = 24,["Kills"] = 49},
        ["Harvest Watcher"] = {["Rank"] = 25,["Kills"] = 49},
        ["Tunnel Rat Forager"] = {["Rank"] = 26,["Kills"] = 48},
        ["Blackrock Outrunner"] = {["Rank"] = 27,["Kills"] = 48},
        ["Stonesplinter Trogg"] = {["Rank"] = 28,["Kills"] = 47},
        ["Dreadmaw Crocolisk"] = {["Rank"] = 29,["Kills"] = 44},
        ["Tunnel Rat Digger"] = {["Rank"] = 30,["Kills"] = 44},
        ["Defias Smuggler"] = {["Rank"] = 31,["Kills"] = 43},
        ["Riverpaw Bandit"] = {["Rank"] = 32,["Kills"] = 42},
        ["Stormscale Wave Rider"] = {["Rank"] = 33,["Kills"] = 42},
        ["Murloc Tidehunter"] = {["Rank"] = 34,["Kills"] = 41},
        ["Venture Co. Enforcer"] = {["Rank"] = 35,["Kills"] = 40},
        ["Ol' Sooty"] = {["Rank"] = 36,["Kills"] = 39},
        ["Defias Pathstalker"] = {["Rank"] = 37,["Kills"] = 38},
        ["Murloc Coastrunner"] = {["Rank"] = 38,["Kills"] = 36},
        ["Imp Minion"] = {["Rank"] = 39,["Kills"] = 35},
        ["Sand Shark"] = {["Rank"] = 40,["Kills"] = 35},
        ["Carnivous the Breaker"] = {["Rank"] = 41,["Kills"] = 35},
        ["Lillith Nefara"] = {["Rank"] = 42,["Kills"] = 34},
        ["Defias Bandit"] = {["Rank"] = 43,["Kills"] = 33},
        ["Stonesplinter Skullthumper"] = {["Rank"] = 44,["Kills"] = 32},
        ["Theramore Marine"] = {["Rank"] = 45,["Kills"] = 32},
        ["Witchwing Slayer"] = {["Rank"] = 46,["Kills"] = 32},
        ["Gnarlpine Shaman"] = {["Rank"] = 47,["Kills"] = 31},
        ["Hecklefang Hyena"] = {["Rank"] = 48,["Kills"] = 31},
        ["Ragefire Trogg"] = {["Rank"] = 49,["Kills"] = 31},
        ["Deepmoss Matriarch"] = {["Rank"] = 50,["Kills"] = 30},
        ["Kodo Matriarch"] = {["Rank"] = 51,["Kills"] = 29},
        ["Rockjaw Skullthumper"] = {["Rank"] = 52,["Kills"] = 29},
        ["Stonesplinter Seer"] = {["Rank"] = 53,["Kills"] = 29},
        ["Kolkar Packhound"] = {["Rank"] = 54,["Kills"] = 29},
        ["Raging Moonkin"] = {["Rank"] = 55,["Kills"] = 29},
        ["Prowler"] = {["Rank"] = 56,["Kills"] = 28},
        ["Kolkar Invader"] = {["Rank"] = 57,["Kills"] = 28},
        ["Hogger"] = {["Rank"] = 58,["Kills"] = 27},
        ["Old Icebeard"] = {["Rank"] = 59,["Kills"] = 27},
        ["Riverpaw Brute"] = {["Rank"] = 60,["Kills"] = 27},
        ["Moonstalker Runt"] = {["Rank"] = 61,["Kills"] = 26},
        ["Greymist Coastrunner"] = {["Rank"] = 62,["Kills"] = 26},
        ["Defias Knuckleduster"] = {["Rank"] = 63,["Kills"] = 26},
        ["Foreman Grills"] = {["Rank"] = 64,["Kills"] = 26},
        ["Burning Blade Fanatic"] = {["Rank"] = 65,["Kills"] = 25},
        ["Dustwind Storm Witch"] = {["Rank"] = 66,["Kills"] = 25},
        ["Southsea Cannoneer"] = {["Rank"] = 67,["Kills"] = 25},
        ["Oggleflint"] = {["Rank"] = 68,["Kills"] = 25},
        ["Dire Condor"] = {["Rank"] = 69,["Kills"] = 25},
        ["Gazz'uz"] = {["Rank"] = 70,["Kills"] = 24},
        ["Gnarlpine Defender"] = {["Rank"] = 71,["Kills"] = 24},
        ["Taskmaster Fizzule"] = {["Rank"] = 72,["Kills"] = 24},
        ["Gnarlpine Augur"] = {["Rank"] = 73,["Kills"] = 23},
        ["Razormane Water Seeker"] = {["Rank"] = 74,["Kills"] = 23},
        ["Murloc Oracle"] = {["Rank"] = 75,["Kills"] = 23},
        ["Venture Co. Overseer"] = {["Rank"] = 76,["Kills"] = 23},
        ["Bristleback Hunter"] = {["Rank"] = 77,["Kills"] = 23},
        ["Blackmoss the Fetid"] = {["Rank"] = 78,["Kills"] = 22},
        ["Stonesplinter Scout"] = {["Rank"] = 79,["Kills"] = 22},
        ["Verog the Dervish"] = {["Rank"] = 80,["Kills"] = 22},
        ["Wretched Bodyguard"] = {["Rank"] = 81,["Kills"] = 22},
        ["Defias Dockmaster"] = {["Rank"] = 82,["Kills"] = 21},
        ["Ornery Plainstrider"] = {["Rank"] = 83,["Kills"] = 21},
        ["Foe Reaper 4000"] = {["Rank"] = 84,["Kills"] = 21},
        ["Compact Harvest Reaper"] = {["Rank"] = 85,["Kills"] = 21},
        ["Xabraxxis"] = {["Rank"] = 86,["Kills"] = 21},
        ["Sri'skulk"] = {["Rank"] = 87,["Kills"] = 20},
        ["Thistle Bear"] = {["Rank"] = 88,["Kills"] = 20},
        ["Bristleback Thornweaver"] = {["Rank"] = 89,["Kills"] = 20},
        ["Expedition Commando"] = {["Rank"] = 90,["Kills"] = 19},
        ["Goretusk"] = {["Rank"] = 91,["Kills"] = 19},
        ["Murloc Netter"] = {["Rank"] = 92,["Kills"] = 19},
        ["Polly"] = {["Rank"] = 93,["Kills"] = 19},
        ["Oakenscowl"] = {["Rank"] = 94,["Kills"] = 18},
        ["Riverpaw Scout"] = {["Rank"] = 95,["Kills"] = 18},
        ["Oasis Snapjaw"] = {["Rank"] = 96,["Kills"] = 18},
        ["Venture Co. Drudger"] = {["Rank"] = 97,["Kills"] = 18},
        ["Witchwing Roguefeather"] = {["Rank"] = 98,["Kills"] = 18},
        ["Dalaran Serpent"] = {["Rank"] = 99,["Kills"] = 18},
        ["Gradok"] = {["Rank"] = 100,["Kills"] = 18},
    }

    MobRank.mobs_2130 = {
        ["Deepmoss Matriarch"] = {["Rank"] = 1,["Kills"] = 60},
        ["Compact Harvest Reaper"] = {["Rank"] = 2,["Kills"] = 46},
        ["Unseen"] = {["Rank"] = 3,["Kills"] = 40},
        ["Razormane Stalker"] = {["Rank"] = 4,["Kills"] = 33},
        ["Stitches"] = {["Rank"] = 5,["Kills"] = 31},
        ["Carver Molsen"] = {["Rank"] = 6,["Kills"] = 21},
        ["Wretched Bodyguard"] = {["Rank"] = 7,["Kills"] = 19},
        ["Dark Strand Assassin"] = {["Rank"] = 8,["Kills"] = 19},
        ["Silithid Swarm"] = {["Rank"] = 9,["Kills"] = 18},
        ["Dragonmaw Raider"] = {["Rank"] = 10,["Kills"] = 17},
        ["Mor'Ladim"] = {["Rank"] = 11,["Kills"] = 16},
        ["Shadowhide Slayer"] = {["Rank"] = 12,["Kills"] = 15},
        ["Wildthorn Lurker"] = {["Rank"] = 13,["Kills"] = 15},
        ["Galak Assassin"] = {["Rank"] = 14,["Kills"] = 15},
        ["Warlord Krom'zar"] = {["Rank"] = 15,["Kills"] = 14},
        ["Goggeroc"] = {["Rank"] = 16,["Kills"] = 14},
        ["Deepmoss Creeper"] = {["Rank"] = 17,["Kills"] = 13},
        ["Defias Raider"] = {["Rank"] = 18,["Kills"] = 13},
        ["Blackrock Sentry"] = {["Rank"] = 19,["Kills"] = 13},
        ["Grunt"] = {["Rank"] = 20,["Kills"] = 12},
        ["Devouring Ectoplasm"] = {["Rank"] = 21,["Kills"] = 12},
        ["Blackrock Champion"] = {["Rank"] = 22,["Kills"] = 11},
        ["Defias Pirate"] = {["Rank"] = 23,["Kills"] = 11},
        ["Aku'mai Snapjaw"] = {["Rank"] = 24,["Kills"] = 11},
        ["Edwin VanCleef"] = {["Rank"] = 25,["Kills"] = 10},
        ["Defias Digger"] = {["Rank"] = 26,["Kills"] = 10},
        ["Blackrock Outrunner"] = {["Rank"] = 27,["Kills"] = 10},
        ["Defias Highwayman"] = {["Rank"] = 28,["Kills"] = 10},
        ["Befouled Water Elemental"] = {["Rank"] = 29,["Kills"] = 10},
        ["Dun Garok Soldier"] = {["Rank"] = 30,["Kills"] = 10},
        ["Cursed Marine"] = {["Rank"] = 31,["Kills"] = 10},
        ["Bael'dun Foreman"] = {["Rank"] = 32,["Kills"] = 9},
        ["Horde Guard"] = {["Rank"] = 33,["Kills"] = 9},
        ["Bael'dun Officer"] = {["Rank"] = 34,["Kills"] = 9},
        ["Defias Overseer"] = {["Rank"] = 35,["Kills"] = 8},
        ["Deviate Creeper"] = {["Rank"] = 36,["Kills"] = 8},
        ["Shadowhide Brute"] = {["Rank"] = 37,["Kills"] = 8},
        ["Blackrock Summoner"] = {["Rank"] = 38,["Kills"] = 8},
        ["Black Widow Hatchling"] = {["Rank"] = 39,["Kills"] = 8},
        ["Flesh Eating Worm"] = {["Rank"] = 40,["Kills"] = 8},
        ["Bloodfury Ambusher"] = {["Rank"] = 41,["Kills"] = 8},
        ["Defias Inmate"] = {["Rank"] = 42,["Kills"] = 8},
        ["Nightbane Shadow Weaver"] = {["Rank"] = 43,["Kills"] = 8},
        ["Hillsbrad Miner"] = {["Rank"] = 44,["Kills"] = 8},
        ["Cursed Sailor"] = {["Rank"] = 45,["Kills"] = 8},
        ["Redridge Basher"] = {["Rank"] = 46,["Kills"] = 7},
        ["Druid of the Fang"] = {["Rank"] = 47,["Kills"] = 7},
        ["Silithid Swarmer"] = {["Rank"] = 48,["Kills"] = 7},
        ["Silithid Grub"] = {["Rank"] = 49,["Kills"] = 7},
        ["Besseleth"] = {["Rank"] = 50,["Kills"] = 7},
        ["Defias Blackguard"] = {["Rank"] = 51,["Kills"] = 7},
        ["Blackrock Shadowcaster"] = {["Rank"] = 52,["Kills"] = 7},
        ["Syndicate Watchman"] = {["Rank"] = 53,["Kills"] = 7},
        ["Bael'dun Excavator"] = {["Rank"] = 54,["Kills"] = 7},
        ["Ghostpaw Alpha"] = {["Rank"] = 55,["Kills"] = 7},
        ["Defias Night Blade"] = {["Rank"] = 56,["Kills"] = 6},
        ["Venture Co. Enforcer"] = {["Rank"] = 57,["Kills"] = 6},
        ["Wrathtail Sea Witch"] = {["Rank"] = 58,["Kills"] = 6},
        ["Deepmoss Venomspitter"] = {["Rank"] = 59,["Kills"] = 6},
        ["Remnants Footman"] = {["Rank"] = 60,["Kills"] = 6},
        ["Bristleback Thornweaver"] = {["Rank"] = 61,["Kills"] = 6},
        ["Bluegill Puddlejumper"] = {["Rank"] = 62,["Kills"] = 6},
        ["Defias Henchman"] = {["Rank"] = 63,["Kills"] = 6},
        ["Defias Squallshaper"] = {["Rank"] = 64,["Kills"] = 6},
        ["Thragomm"] = {["Rank"] = 65,["Kills"] = 6},
        ["Skeletal Horror"] = {["Rank"] = 66,["Kills"] = 6},
        ["Skeletal Miner"] = {["Rank"] = 67,["Kills"] = 6},
        ["Bael'dun Rifleman"] = {["Rank"] = 68,["Kills"] = 6},
        ["Slavering Worg"] = {["Rank"] = 69,["Kills"] = 6},
        ["Yowler"] = {["Rank"] = 70,["Kills"] = 6},
        ["Lupine Horror"] = {["Rank"] = 71,["Kills"] = 6},
        ["Bloodfury Ripper"] = {["Rank"] = 72,["Kills"] = 6},
        ["Bleak Worg"] = {["Rank"] = 73,["Kills"] = 6},
        ["Aku'mai Servant"] = {["Rank"] = 74,["Kills"] = 6},
        ["Dragonmaw Scout"] = {["Rank"] = 75,["Kills"] = 5},
        ["Imp Minion"] = {["Rank"] = 76,["Kills"] = 5},
        ["Bristleback Hunter"] = {["Rank"] = 77,["Kills"] = 5},
        ["Redridge Alpha"] = {["Rank"] = 78,["Kills"] = 5},
        ["Dragonmaw Grunt"] = {["Rank"] = 79,["Kills"] = 5},
        ["Greymist Coastrunner"] = {["Rank"] = 80,["Kills"] = 5},
        ["Undead Dynamiter"] = {["Rank"] = 81,["Kills"] = 5},
        ["Marcus Bel"] = {["Rank"] = 82,["Kills"] = 5},
        ["Silithid Creeper"] = {["Rank"] = 83,["Kills"] = 5},
        ["Necromancer Reginald"] = {["Rank"] = 84,["Kills"] = 5},
        ["Kolkar Invader"] = {["Rank"] = 85,["Kills"] = 5},
        ["Windshear Digger"] = {["Rank"] = 86,["Kills"] = 5},
        ["Hannah Bladeleaf"] = {["Rank"] = 87,["Kills"] = 5},
        ["Mosshide Brute"] = {["Rank"] = 88,["Kills"] = 5},
        ["Eliza's Guard"] = {["Rank"] = 89,["Kills"] = 5},
        ["Nightbane Dark Runner"] = {["Rank"] = 90,["Kills"] = 5},
        ["Lupine Delusion"] = {["Rank"] = 91,["Kills"] = 5},
        ["Defias Prisoner"] = {["Rank"] = 92,["Kills"] = 5},
        ["Dragonmaw Bonewarder"] = {["Rank"] = 93,["Kills"] = 5},
        ["Slim's Friend"] = {["Rank"] = 94,["Kills"] = 5},
        ["Redridge Brute"] = {["Rank"] = 95,["Kills"] = 4},
        ["Deepmoss Hatchling"] = {["Rank"] = 96,["Kills"] = 4},
        ["Murloc Tidehunter"] = {["Rank"] = 97,["Kills"] = 4},
        ["Taskmaster Fizzule"] = {["Rank"] = 98,["Kills"] = 4},
        ["Foreman Klix"] = {["Rank"] = 99,["Kills"] = 4},
        ["Mo'grosh Ogre"] = {["Rank"] = 100,["Kills"] = 4},
    }

    MobRank.mobs_3140 = {
        ["Unseen"] = {["Rank"] = 1,["Kills"] = 28},
        ["Blastmaster Emi Shortfuse"] = {["Rank"] = 2,["Kills"] = 17},
        ["Warleader Kintoza"] = {["Rank"] = 3,["Kills"] = 12},
        ["Undead Ravager"] = {["Rank"] = 4,["Kills"] = 11},
        ["Deranged Ancient"] = {["Rank"] = 5,["Kills"] = 11},
        ["Kurzen Commando"] = {["Rank"] = 6,["Kills"] = 10},
        ["Dragonmaw Raider"] = {["Rank"] = 7,["Kills"] = 9},
        ["Slim's Friend"] = {["Rank"] = 8,["Kills"] = 7},
        ["Nightbane Dark Runner"] = {["Rank"] = 9,["Kills"] = 6},
        ["Screeching Harpy"] = {["Rank"] = 10,["Kills"] = 6},
        ["Grenka Bloodscreech"] = {["Rank"] = 11,["Kills"] = 6},
        ["Burning Blade Felsworn"] = {["Rank"] = 12,["Kills"] = 6},
        ["Barrens Guard"] = {["Rank"] = 13,["Kills"] = 5},
        ["Dun Garok Mountaineer"] = {["Rank"] = 14,["Kills"] = 5},
        ["Tarren Mill Deathguard"] = {["Rank"] = 15,["Kills"] = 5},
        ["Mosh'Ogg Warmonger"] = {["Rank"] = 16,["Kills"] = 5},
        ["Magrami Spectre"] = {["Rank"] = 17,["Kills"] = 5},
        ["Darkmist Silkspinner"] = {["Rank"] = 18,["Kills"] = 5},
        ["Aku'mai Snapjaw"] = {["Rank"] = 19,["Kills"] = 4},
        ["Southshore Guard"] = {["Rank"] = 20,["Kills"] = 4},
        ["Scarlet Monk"] = {["Rank"] = 21,["Kills"] = 4},
        ["Syndicate Wizard"] = {["Rank"] = 22,["Kills"] = 4},
        ["Elder Saltwater Crocolisk"] = {["Rank"] = 23,["Kills"] = 4},
        ["Kolkar Destroyer"] = {["Rank"] = 24,["Kills"] = 4},
        ["Bloodscalp Scout"] = {["Rank"] = 25,["Kills"] = 4},
        ["Hillsbrad Miner"] = {["Rank"] = 26,["Kills"] = 3},
        ["Syndicate Thief"] = {["Rank"] = 27,["Kills"] = 3},
        ["Galak Assassin"] = {["Rank"] = 28,["Kills"] = 3},
        ["Scarlet Torturer"] = {["Rank"] = 29,["Kills"] = 3},
        ["Magus Palon"] = {["Rank"] = 30,["Kills"] = 3},
        ["Chieftain Nek'rosh"] = {["Rank"] = 31,["Kills"] = 3},
        ["Dalaran Theurgist"] = {["Rank"] = 32,["Kills"] = 3},
        ["Scorpid Reaver"] = {["Rank"] = 33,["Kills"] = 3},
        ["Defias Convict"] = {["Rank"] = 34,["Kills"] = 3},
        ["Captain Ironhill"] = {["Rank"] = 35,["Kills"] = 3},
        ["Syndicate Prowler"] = {["Rank"] = 36,["Kills"] = 3},
        ["Stromgarde Cavalryman"] = {["Rank"] = 37,["Kills"] = 3},
        ["Kurzen War Tiger"] = {["Rank"] = 38,["Kills"] = 3},
        ["Holdout Medic"] = {["Rank"] = 39,["Kills"] = 3},
        ["Kurzen Jungle Fighter"] = {["Rank"] = 40,["Kills"] = 3},
        ["Maraudine Wrangler"] = {["Rank"] = 41,["Kills"] = 3},
        ["Scarlet Gallant"] = {["Rank"] = 42,["Kills"] = 3},
        ["Saltscale Warrior"] = {["Rank"] = 43,["Kills"] = 3},
        ["Bloodsail Raider"] = {["Rank"] = 44,["Kills"] = 3},
        ["Maraudine Bonepaw"] = {["Rank"] = 45,["Kills"] = 3},
        ["Tethis"] = {["Rank"] = 46,["Kills"] = 3},
        ["Dalaran Shield Guard"] = {["Rank"] = 47,["Kills"] = 2},
        ["Defias Prisoner"] = {["Rank"] = 48,["Kills"] = 2},
        ["Felguard"] = {["Rank"] = 49,["Kills"] = 2},
        ['Tapoke "Slim" Jahn'] = {["Rank"] = 50,["Kills"] = 2},
        ["Razorfen Thornweaver"] = {["Rank"] = 51,["Kills"] = 2},
        ["Dark Iron Tunneler"] = {["Rank"] = 52,["Kills"] = 2},
        ["Dun Garok Soldier"] = {["Rank"] = 53,["Kills"] = 2},
        ["Stitches"] = {["Rank"] = 54,["Kills"] = 2},
        ["Bael'dun Soldier"] = {["Rank"] = 55,["Kills"] = 2},
        ["Morbent Fel"] = {["Rank"] = 56,["Kills"] = 2},
        ["Voidwalker"] = {["Rank"] = 57,["Kills"] = 2},
        ["Defias Rioter"] = {["Rank"] = 58,["Kills"] = 2},
        ["Mor'Ladim"] = {["Rank"] = 59,["Kills"] = 2},
        ["Bael'dun Officer"] = {["Rank"] = 60,["Kills"] = 2},
        ["Scarlet Sentry"] = {["Rank"] = 61,["Kills"] = 2},
        ["Grunt"] = {["Rank"] = 62,["Kills"] = 2},
        ["Dabyrie Laborer"] = {["Rank"] = 63,["Kills"] = 2},
        ["Stalvan Mistmantle"] = {["Rank"] = 64,["Kills"] = 2},
        ["Horde Grunt"] = {["Rank"] = 65,["Kills"] = 2},
        ["Crushridge Mauler"] = {["Rank"] = 66,["Kills"] = 2},
        ["Plague Spreader"] = {["Rank"] = 67,["Kills"] = 2},
        ["Witherbark Shadow Hunter"] = {["Rank"] = 68,["Kills"] = 2},
        ["Holdout Warrior"] = {["Rank"] = 69,["Kills"] = 2},
        ["Magram Pack Runner"] = {["Rank"] = 70,["Kills"] = 2},
        ["Drywhisker Digger"] = {["Rank"] = 71,["Kills"] = 2},
        ["Singer"] = {["Rank"] = 72,["Kills"] = 2},
        ["Disturbed Spirit"] = {["Rank"] = 73,["Kills"] = 2},
        ["Skhowl"] = {["Rank"] = 74,["Kills"] = 2},
        ["Crushridge Warmonger"] = {["Rank"] = 75,["Kills"] = 2},
        ["Saltscale Oracle"] = {["Rank"] = 76,["Kills"] = 2},
        ["Highland Thrasher"] = {["Rank"] = 77,["Kills"] = 2},
        ["Mechanized Guardian"] = {["Rank"] = 78,["Kills"] = 2},
        ["Crushridge Ogre"] = {["Rank"] = 79,["Kills"] = 2},
        ["Coral Shark"] = {["Rank"] = 80,["Kills"] = 2},
        ["Bhag'thera"] = {["Rank"] = 81,["Kills"] = 2},
        ["Techbot"] = {["Rank"] = 82,["Kills"] = 2},
        ["Sorrow Spinner"] = {["Rank"] = 83,["Kills"] = 2},
        ["Witherbark Headhunter"] = {["Rank"] = 84,["Kills"] = 2},
        ["Witherbark Rogue"] = {["Rank"] = 85,["Kills"] = 2},
        ["Blackhorn Warrior"] = {["Rank"] = 86,["Kills"] = 2},
        ["Witherbark Raider"] = {["Rank"] = 87,["Kills"] = 2},
        ["Scorpashi Venomlash"] = {["Rank"] = 88,["Kills"] = 2},
        ["Stranglethorn Raptor"] = {["Rank"] = 89,["Kills"] = 2},
        ["Refuge Pointe Defender"] = {["Rank"] = 90,["Kills"] = 2},
        ["Bloodscalp Mystic"] = {["Rank"] = 91,["Kills"] = 2},
        ["Stonard Grunt"] = {["Rank"] = 92,["Kills"] = 2},
        ["Lord Aliden Perenolde"] = {["Rank"] = 93,["Kills"] = 2},
        ["Boneflayer Ghoul"] = {["Rank"] = 94,["Kills"] = 2},
        ["Fallenroot Satyr"] = {["Rank"] = 95,["Kills"] = 1},
        ["Bleakheart Shadowstalker"] = {["Rank"] = 96,["Kills"] = 1},
        ["Bluegill Raider"] = {["Rank"] = 97,["Kills"] = 1},
        ["Murkshallow Softshell"] = {["Rank"] = 98,["Kills"] = 1},
        ["Aean Swiftriver"] = {["Rank"] = 99,["Kills"] = 1},
        ["Deepstrider Giant"] = {["Rank"] = 100,["Kills"] = 1},
    }

    MobRank.mobs_4159 = {
        ["Fleet Master Firallon"] = {["Rank"] = 1,["Kills"] = 10},
        ["Firemane Scout"] = {["Rank"] = 2,["Kills"] = 5},
        ["Magrami Spectre"] = {["Rank"] = 3,["Kills"] = 4},
        ["Firemane Ash Tail"] = {["Rank"] = 4,["Kills"] = 4},
        ["Khan Hratha"] = {["Rank"] = 5,["Kills"] = 4},
        ["Wastewander Assassin"] = {["Rank"] = 6,["Kills"] = 4},
        ["Grol the Destroyer"] = {["Rank"] = 7,["Kills"] = 4},
        ["Maraudine Wrangler"] = {["Rank"] = 8,["Kills"] = 3},
        ["Witherbark Felhunter"] = {["Rank"] = 9,["Kills"] = 3},
        ["Gorishi Hive Guard"] = {["Rank"] = 10,["Kills"] = 3},
        ["Xalvic Blackclaw"] = {["Rank"] = 11,["Kills"] = 3},
        ["Fallen Hero"] = {["Rank"] = 12,["Kills"] = 3},
        ["Hive'Ashi Drone"] = {["Rank"] = 13,["Kills"] = 3},
        ["Undead Ravager"] = {["Rank"] = 14,["Kills"] = 2},
        ["Konda"] = {["Rank"] = 15,["Kills"] = 2},
        ["Drywallow Daggermaw"] = {["Rank"] = 16,["Kills"] = 2},
        ["Ironpatch"] = {["Rank"] = 17,["Kills"] = 2},
        ["Zetharia"] = {["Rank"] = 18,["Kills"] = 2},
        ["Blisterpaw Hyena"] = {["Rank"] = 19,["Kills"] = 2},
        ["Grimtotem Naturalist"] = {["Rank"] = 20,["Kills"] = 2},
        ["Hatecrest Serpent Guard"] = {["Rank"] = 21,["Kills"] = 2},
        ["Zul'Farrak Zombie"] = {["Rank"] = 22,["Kills"] = 2},
        ["Scorpid Hunter"] = {["Rank"] = 23,["Kills"] = 2},
        ["Stonevault Mauler"] = {["Rank"] = 24,["Kills"] = 2},
        ["Shay Leafrunner"] = {["Rank"] = 25,["Kills"] = 2},
        ["Vile Priestess Hexx"] = {["Rank"] = 26,["Kills"] = 2},
        ["Vilebranch Raiding Wolf"] = {["Rank"] = 27,["Kills"] = 2},
        ["Un'Goro Thunderer"] = {["Rank"] = 28,["Kills"] = 2},
        ["Vilebranch Kidnapper"] = {["Rank"] = 29,["Kills"] = 2},
        ["Jaedenar Adept"] = {["Rank"] = 30,["Kills"] = 2},
        ["Jaedenar Cultist"] = {["Rank"] = 31,["Kills"] = 2},
        ["Crimson Bodyguard"] = {["Rank"] = 32,["Kills"] = 2},
        ["Bhag'thera"] = {["Rank"] = 33,["Kills"] = 1},
        ["Shadowforge Warrior"] = {["Rank"] = 34,["Kills"] = 1},
        ["Den Grunt"] = {["Rank"] = 35,["Kills"] = 1},
        ["Maraudine Bonepaw"] = {["Rank"] = 36,["Kills"] = 1},
        ["Starving Blisterpaw"] = {["Rank"] = 37,["Kills"] = 1},
        ["Longtooth Runner"] = {["Rank"] = 38,["Kills"] = 1},
        ["Bloodsail Warlock"] = {["Rank"] = 39,["Kills"] = 1},
        ["Drywallow Snapper"] = {["Rank"] = 40,["Kills"] = 1},
        ["Jailor Borhuin"] = {["Rank"] = 41,["Kills"] = 1},
        ["Ridge Stalker"] = {["Rank"] = 42,["Kills"] = 1},
        ["Bloodscalp Mystic"] = {["Rank"] = 43,["Kills"] = 1},
        ["Skullsplitter Panther"] = {["Rank"] = 44,["Kills"] = 1},
        ["Otto"] = {["Rank"] = 45,["Kills"] = 1},
        ["Tethis"] = {["Rank"] = 46,["Kills"] = 1},
        ["Bloodscalp Hunter"] = {["Rank"] = 47,["Kills"] = 1},
        ["Unseen"] = {["Rank"] = 48,["Kills"] = 1},
        ["Bloodsail Sea Dog"] = {["Rank"] = 49,["Kills"] = 1},
        ["Zanzil Naga"] = {["Rank"] = 50,["Kills"] = 1},
        ["Outcast Necromancer"] = {["Rank"] = 51,["Kills"] = 1},
        ["Mirefin Puddlejumper"] = {["Rank"] = 52,["Kills"] = 1},
        ["Baelfyr"] = {["Rank"] = 53,["Kills"] = 1},
        ["Bloodsail Elder Magus"] = {["Rank"] = 54,["Kills"] = 1},
        ["Boulderfist Lord"] = {["Rank"] = 55,["Kills"] = 1},
        ["Giant Darkfang Spider"] = {["Rank"] = 56,["Kills"] = 1},
        ["Saltscale Oracle"] = {["Rank"] = 57,["Kills"] = 1},
        ["Fozruk"] = {["Rank"] = 58,["Kills"] = 1},
        ["Saltscale Tide Lord"] = {["Rank"] = 59,["Kills"] = 1},
        ["Gordunni Brute"] = {["Rank"] = 60,["Kills"] = 1},
        ["Giant Plains Creeper"] = {["Rank"] = 61,["Kills"] = 1},
        ["Boulderfist Enforcer"] = {["Rank"] = 62,["Kills"] = 1},
        ["Saltscale Forager"] = {["Rank"] = 63,["Kills"] = 1},
        ["Aged Kodo"] = {["Rank"] = 64,["Kills"] = 1},
        ["Defias Rioter"] = {["Rank"] = 65,["Kills"] = 1},
        ["Scalebane Captain"] = {["Rank"] = 66,["Kills"] = 1},
        ["Gorlash"] = {["Rank"] = 67,["Kills"] = 1},
        ["Bloodsail Raider"] = {["Rank"] = 68,["Kills"] = 1},
        ["Mirefin Muckdweller"] = {["Rank"] = 69,["Kills"] = 1},
        ["Darkmist Widow"] = {["Rank"] = 70,["Kills"] = 1},
        ["Hive'Ashi Swarmer"] = {["Rank"] = 71,["Kills"] = 1},
        ["Kurzen Elite"] = {["Rank"] = 72,["Kills"] = 1},
        ["Southern Sand Crawler"] = {["Rank"] = 73,["Kills"] = 1},
        ["Daggerspine Sorceress"] = {["Rank"] = 74,["Kills"] = 1},
        ["Elder Saltwater Crocolisk"] = {["Rank"] = 75,["Kills"] = 1},
        ["Firemane Scalebane"] = {["Rank"] = 76,["Kills"] = 1},
        ["Kurzen Subchief"] = {["Rank"] = 77,["Kills"] = 1},
        ["Zanzil Witch Doctor"] = {["Rank"] = 78,["Kills"] = 1},
        ["Lord Shalzaru"] = {["Rank"] = 79,["Kills"] = 1},
        ["Thenan"] = {["Rank"] = 80,["Kills"] = 1},
        ["Stonard Grunt"] = {["Rank"] = 81,["Kills"] = 1},
        ["Darkmist Silkspinner"] = {["Rank"] = 82,["Kills"] = 1},
        ["Gordok Ogre-Mage"] = {["Rank"] = 83,["Kills"] = 1},
        ["Woodpaw Mongrel"] = {["Rank"] = 84,["Kills"] = 1},
        ["Bloodfen Scytheclaw"] = {["Rank"] = 85,["Kills"] = 1},
        ["Witherbark Bloodling"] = {["Rank"] = 86,["Kills"] = 1},
        ["Jaguero Stalker"] = {["Rank"] = 87,["Kills"] = 1},
        ["Deathstrike Tarantula"] = {["Rank"] = 88,["Kills"] = 1},
        ["Bloodsail Mage"] = {["Rank"] = 89,["Kills"] = 1},
        ["Sprite Darter"] = {["Rank"] = 90,["Kills"] = 1},
        ["Mokk the Savage"] = {["Rank"] = 91,["Kills"] = 1},
        ["Kurzen Shadow Hunter"] = {["Rank"] = 92,["Kills"] = 1},
        ["Wastewander Shadow Mage"] = {["Rank"] = 93,["Kills"] = 1},
        ["Enraged Feral Scar"] = {["Rank"] = 94,["Kills"] = 1},
        ["Mosh'Ogg Warmonger"] = {["Rank"] = 95,["Kills"] = 1},
        ["Magma Elemental"] = {["Rank"] = 96,["Kills"] = 1},
        ["Vault Warder"] = {["Rank"] = 97,["Kills"] = 1},
        ["Skullsplitter Axe Thrower"] = {["Rank"] = 98,["Kills"] = 1},
        ["Vilebranch Wolf Pup"] = {["Rank"] = 99,["Kills"] = 1},
        ["Dark Iron Agent"] = {["Rank"] = 100,["Kills"] = 1},
    }

    MobRank.players = {
        ["Valkar"] = {["Rank"] = 1,["Kills"] = 125},
        ["Zdraxus"] = {["Rank"] = 2,["Kills"] = 11},
        ["Grimus"] = {["Rank"] = 3,["Kills"] = 9},
        ["Lilrat"] = {["Rank"] = 4,["Kills"] = 8},
        ["Dimkosyan"] = {["Rank"] = 5,["Kills"] = 8},
        ["Greengnom"] = {["Rank"] = 6,["Kills"] = 7},
        ["Slimshadowy"] = {["Rank"] = 7,["Kills"] = 7},
        ["Evolvz"] = {["Rank"] = 8,["Kills"] = 6},
        ["Bamboozler"] = {["Rank"] = 9,["Kills"] = 5},
        ["Jimmycarrey"] = {["Rank"] = 10,["Kills"] = 5},
        ["Doob"] = {["Rank"] = 11,["Kills"] = 5},
        ["Eemodru"] = {["Rank"] = 12,["Kills"] = 4},
        ["Glin"] = {["Rank"] = 13,["Kills"] = 4},
        ["Shadist"] = {["Rank"] = 14,["Kills"] = 4},
        ["Gevilgaz"] = {["Rank"] = 15,["Kills"] = 4},
        ["Pekora"] = {["Rank"] = 16,["Kills"] = 4},
        ["Yourmotherr"] = {["Rank"] = 17,["Kills"] = 3},
        ["Elkrinia"] = {["Rank"] = 18,["Kills"] = 3},
        ["Zaradur"] = {["Rank"] = 19,["Kills"] = 3},
        ["Shacklez"] = {["Rank"] = 20,["Kills"] = 3},
        ["Proy"] = {["Rank"] = 21,["Kills"] = 3},
        ["Mossadagent"] = {["Rank"] = 22,["Kills"] = 3},
        ["Sammara"] = {["Rank"] = 23,["Kills"] = 2},
        ["Mangomazestv"] = {["Rank"] = 24,["Kills"] = 2},
        ["Turzog"] = {["Rank"] = 25,["Kills"] = 2},
        ["Arkimonday"] = {["Rank"] = 26,["Kills"] = 2},
        ["Zilberman"] = {["Rank"] = 27,["Kills"] = 2},
        ["Akmetlt"] = {["Rank"] = 28,["Kills"] = 2},
        ["Nestro"] = {["Rank"] = 29,["Kills"] = 2},
        ["Lichking"] = {["Rank"] = 30,["Kills"] = 2},
        ["Deaddy"] = {["Rank"] = 31,["Kills"] = 2},
        ["Gungner"] = {["Rank"] = 32,["Kills"] = 2},
        ["Massorcist"] = {["Rank"] = 33,["Kills"] = 2},
        ["Jahh"] = {["Rank"] = 34,["Kills"] = 2},
        ["Shortstab"] = {["Rank"] = 35,["Kills"] = 2},
        ["Orcisassault"] = {["Rank"] = 36,["Kills"] = 2},
        ["Petrichor"] = {["Rank"] = 37,["Kills"] = 2},
        ["Forskintaker"] = {["Rank"] = 38,["Kills"] = 2},
        ["Olinson"] = {["Rank"] = 39,["Kills"] = 2},
        ["Med"] = {["Rank"] = 40,["Kills"] = 2},
        ["Chicagobulls"] = {["Rank"] = 41,["Kills"] = 2},
        ["Zaas"] = {["Rank"] = 42,["Kills"] = 2},
        ["Bloats"] = {["Rank"] = 43,["Kills"] = 2},
        ["Ripbozohaha"] = {["Rank"] = 44,["Kills"] = 2},
        ["Chrisophia"] = {["Rank"] = 45,["Kills"] = 2},
        ["Greenpepe"] = {["Rank"] = 46,["Kills"] = 2},
        ["Wipeout"] = {["Rank"] = 47,["Kills"] = 1},
        ["Deadelivery"] = {["Rank"] = 48,["Kills"] = 1},
        ["Gyp"] = {["Rank"] = 49,["Kills"] = 1},
        ["Nightmeow"] = {["Rank"] = 50,["Kills"] = 1},
        ["Maeryll"] = {["Rank"] = 51,["Kills"] = 1},
        ["Stabby"] = {["Rank"] = 52,["Kills"] = 1},
        ["Windtop"] = {["Rank"] = 53,["Kills"] = 1},
        ["Trentx"] = {["Rank"] = 54,["Kills"] = 1},
        ["Rendle"] = {["Rank"] = 55,["Kills"] = 1},
        ["Faelwrynn"] = {["Rank"] = 56,["Kills"] = 1},
        ["Deca"] = {["Rank"] = 57,["Kills"] = 1},
        ["Mostwanted"] = {["Rank"] = 58,["Kills"] = 1},
        ["Fitslag"] = {["Rank"] = 59,["Kills"] = 1},
        ["Wotanjugend"] = {["Rank"] = 60,["Kills"] = 1},
        ["Lodr"] = {["Rank"] = 61,["Kills"] = 1},
        ["Lorivel"] = {["Rank"] = 62,["Kills"] = 1},
        ["Elwynboss"] = {["Rank"] = 63,["Kills"] = 1},
        ["Bootiebandit"] = {["Rank"] = 64,["Kills"] = 1},
        ["Komowa"] = {["Rank"] = 65,["Kills"] = 1},
        ["Crabpower"] = {["Rank"] = 66,["Kills"] = 1},
        ["Greenkevin"] = {["Rank"] = 67,["Kills"] = 1},
        ["Schneider"] = {["Rank"] = 68,["Kills"] = 1},
        ["Leprekon"] = {["Rank"] = 69,["Kills"] = 1},
        ["Grovestalker"] = {["Rank"] = 70,["Kills"] = 1},
        ["Tokyomane"] = {["Rank"] = 71,["Kills"] = 1},
        ["Grizzlie"] = {["Rank"] = 72,["Kills"] = 1},
        ["Blackbiird"] = {["Rank"] = 73,["Kills"] = 1},
        ["Bedsteven"] = {["Rank"] = 74,["Kills"] = 1},
        ["Peacelocke"] = {["Rank"] = 75,["Kills"] = 1},
        ["Abwxo"] = {["Rank"] = 76,["Kills"] = 1},
        ["Darkharon"] = {["Rank"] = 77,["Kills"] = 1},
        ["Fante"] = {["Rank"] = 78,["Kills"] = 1},
        ["Biz"] = {["Rank"] = 79,["Kills"] = 1},
        ["Shahjine"] = {["Rank"] = 80,["Kills"] = 1},
        ["Jabun"] = {["Rank"] = 81,["Kills"] = 1},
        ["Dmn"] = {["Rank"] = 82,["Kills"] = 1},
        ["Lahvovic"] = {["Rank"] = 83,["Kills"] = 1},
        ["Alyara"] = {["Rank"] = 84,["Kills"] = 1},
        ["Cato"] = {["Rank"] = 85,["Kills"] = 1},
        ["Funjke"] = {["Rank"] = 86,["Kills"] = 1},
        ["Rhazhai"] = {["Rank"] = 87,["Kills"] = 1},
        ["Outlast"] = {["Rank"] = 88,["Kills"] = 1},
        ["Jimmymckill"] = {["Rank"] = 89,["Kills"] = 1},
        ["Idk"] = {["Rank"] = 90,["Kills"] = 1},
        ["Smoak"] = {["Rank"] = 91,["Kills"] = 1},
        ["Savitar"] = {["Rank"] = 92,["Kills"] = 1},
        ["Megalomaniac"] = {["Rank"] = 93,["Kills"] = 1},
        ["Jazzpolice"] = {["Rank"] = 94,["Kills"] = 1},
        ["Abcde"] = {["Rank"] = 95,["Kills"] = 1},
        ["Azzerz"] = {["Rank"] = 96,["Kills"] = 1},
        ["Buranku"] = {["Rank"] = 97,["Kills"] = 1},
        ["Yosemitesam"] = {["Rank"] = 98,["Kills"] = 1},
        ["Catfat"] = {["Rank"] = 99,["Kills"] = 1},
        ["Shiimanee"] = {["Rank"] = 100,["Kills"] = 1},
    }
end