MobRank.mobs = {
    -- NPCs
    ["Defias Bodyguard"] = {["Rank"] = 1,["Kills"] = 235},
    ["Defias Highwayman"] = {["Rank"] = 2,["Kills"] = 172},
    ["Defias Trapper"] = {["Rank"] = 3,["Kills"] = 148},
    ["Rockjaw Bonesnapper"] = {["Rank"] = 4,["Kills"] = 115},
    ["Deepmoss Matriarch"] = {["Rank"] = 5,["Kills"] = 89},
    ["Tunnel Rat Geomancer"] = {["Rank"] = 6,["Kills"] = 87},
    ["Vagash"] = {["Rank"] = 7,["Kills"] = 81},
    ["Carver Molsen"] = {["Rank"] = 8,["Kills"] = 78},
    ["Sunscale Scytheclaw"] = {["Rank"] = 9,["Kills"] = 76},
    ["Voidwalker"] = {["Rank"] = 10,["Kills"] = 70},
    ["Unseen"] = {["Rank"] = 11,["Kills"] = 69},
    ["Warlord Krom'zar"] = {["Rank"] = 12,["Kills"] = 69},
    ["Lunaclaw"] = {["Rank"] = 13,["Kills"] = 67},
    ["Rotting Ancestor"] = {["Rank"] = 14,["Kills"] = 65},
    ["Compact Harvest Reaper"] = {["Rank"] = 15,["Kills"] = 62},
    ["Defias Pillager"] = {["Rank"] = 16,["Kills"] = 61},
    ["Burning Blade Apprentice"] = {["Rank"] = 17,["Kills"] = 58},
    ["Bristleback Trapper"] = {["Rank"] = 18,["Kills"] = 58},
    ["Fizzle Darkstorm"] = {["Rank"] = 19,["Kills"] = 56},
    ["Son of Arugal"] = {["Rank"] = 20,["Kills"] = 55},
    ["Razormane Defender"] = {["Rank"] = 21,["Kills"] = 54},
    ["Defias Looter"] = {["Rank"] = 22,["Kills"] = 54},
    ["Blackrock Outrunner"] = {["Rank"] = 23,["Kills"] = 54},
    ["Tunnel Rat Kobold"] = {["Rank"] = 24,["Kills"] = 52},
    ["Riverpaw Outrunner"] = {["Rank"] = 25,["Kills"] = 51},
    ["Burning Blade Toxicologist"] = {["Rank"] = 26,["Kills"] = 50},
    ["Benny Blaanco"] = {["Rank"] = 27,["Kills"] = 49},
    ["Longsnout"] = {["Rank"] = 28,["Kills"] = 48},
    ["Tunnel Rat Forager"] = {["Rank"] = 29,["Kills"] = 46},
    ["Harvest Watcher"] = {["Rank"] = 30,["Kills"] = 46},
    ["Stonesplinter Trogg"] = {["Rank"] = 31,["Kills"] = 46},
    ["Murloc Tidehunter"] = {["Rank"] = 32,["Kills"] = 45},
    ["Venture Co. Enforcer"] = {["Rank"] = 33,["Kills"] = 45},
    ["Dreadmaw Crocolisk"] = {["Rank"] = 34,["Kills"] = 44},
    ["Defias Smuggler"] = {["Rank"] = 35,["Kills"] = 41},
    ["Riverpaw Bandit"] = {["Rank"] = 36,["Kills"] = 41},
    ["Ol' Sooty"] = {["Rank"] = 37,["Kills"] = 41},
    ["Wretched Bodyguard"] = {["Rank"] = 38,["Kills"] = 40},
    ["Stormscale Wave Rider"] = {["Rank"] = 39,["Kills"] = 40},
    ["Tunnel Rat Digger"] = {["Rank"] = 40,["Kills"] = 39},
    ["Defias Pathstalker"] = {["Rank"] = 41,["Kills"] = 39},
    ["Stitches"] = {["Rank"] = 42,["Kills"] = 38},
    ["Imp Minion"] = {["Rank"] = 43,["Kills"] = 38},
    ["Razormane Stalker"] = {["Rank"] = 44,["Kills"] = 36},
    ["Carnivous the Breaker"] = {["Rank"] = 45,["Kills"] = 35},
    ["Murloc Coastrunner"] = {["Rank"] = 46,["Kills"] = 34},
    ["Sand Shark"] = {["Rank"] = 47,["Kills"] = 34},
    ["Theramore Marine"] = {["Rank"] = 48,["Kills"] = 34},
    ["Ragefire Trogg"] = {["Rank"] = 49,["Kills"] = 34},
    ["Stonesplinter Skullthumper"] = {["Rank"] = 50,["Kills"] = 33},
    ["Witchwing Slayer"] = {["Rank"] = 51,["Kills"] = 33},
    ["Lillith Nefara"] = {["Rank"] = 52,["Kills"] = 32},
    ["Kolkar Invader"] = {["Rank"] = 53,["Kills"] = 32},
    ["Defias Bandit"] = {["Rank"] = 54,["Kills"] = 32},
    ["Hecklefang Hyena"] = {["Rank"] = 55,["Kills"] = 32},
    ["Gnarlpine Shaman"] = {["Rank"] = 56,["Kills"] = 31},
    ["Greymist Coastrunner"] = {["Rank"] = 57,["Kills"] = 31},
    ["Silithid Swarm"] = {["Rank"] = 58,["Kills"] = 30},
    ["Raging Moonkin"] = {["Rank"] = 59,["Kills"] = 29},
    ["Kodo Matriarch"] = {["Rank"] = 60,["Kills"] = 29},
    ["Kolkar Packhound"] = {["Rank"] = 61,["Kills"] = 29},
    ["Rockjaw Skullthumper"] = {["Rank"] = 62,["Kills"] = 28},
    ["Hogger"] = {["Rank"] = 63,["Kills"] = 28},
    ["Foreman Grills"] = {["Rank"] = 64,["Kills"] = 27},
    ["Old Icebeard"] = {["Rank"] = 65,["Kills"] = 27},
    ["Taskmaster Fizzule"] = {["Rank"] = 66,["Kills"] = 27},
    ["Riverpaw Brute"] = {["Rank"] = 67,["Kills"] = 27},
    ["Dragonmaw Raider"] = {["Rank"] = 68,["Kills"] = 27},
    ["Bristleback Hunter"] = {["Rank"] = 69,["Kills"] = 27},
    ["Stonesplinter Seer"] = {["Rank"] = 70,["Kills"] = 27},
    ["Moonstalker Runt"] = {["Rank"] = 71,["Kills"] = 26},
    ["Prowler"] = {["Rank"] = 72,["Kills"] = 26},
    ["Defias Knuckleduster"] = {["Rank"] = 73,["Kills"] = 25},
    ["Southsea Cannoneer"] = {["Rank"] = 74,["Kills"] = 25},
    ["Burning Blade Fanatic"] = {["Rank"] = 75,["Kills"] = 25},
    ["Oggleflint"] = {["Rank"] = 76,["Kills"] = 25},
    ["Bristleback Thornweaver"] = {["Rank"] = 77,["Kills"] = 24},
    ["Dire Condor"] = {["Rank"] = 78,["Kills"] = 24},
    ["Dustwind Storm Witch"] = {["Rank"] = 79,["Kills"] = 24},
    ["Venture Co. Overseer"] = {["Rank"] = 80,["Kills"] = 24},
    ["Ornery Plainstrider"] = {["Rank"] = 81,["Kills"] = 23},
    ["Verog the Dervish"] = {["Rank"] = 82,["Kills"] = 23},
    ["Razormane Water Seeker"] = {["Rank"] = 83,["Kills"] = 23},
    ["Gnarlpine Defender"] = {["Rank"] = 84,["Kills"] = 23},
    ["Gazz'uz"] = {["Rank"] = 85,["Kills"] = 23},
    ["Foe Reaper 4000"] = {["Rank"] = 86,["Kills"] = 22},
    ["Blackmoss the Fetid"] = {["Rank"] = 87,["Kills"] = 22},
    ["Murloc Oracle"] = {["Rank"] = 88,["Kills"] = 22},
    ["Defias Dockmaster"] = {["Rank"] = 89,["Kills"] = 21},
    ["Gnarlpine Augur"] = {["Rank"] = 90,["Kills"] = 21},
    ["Dalaran Serpent"] = {["Rank"] = 91,["Kills"] = 21},
    ["Thistle Bear"] = {["Rank"] = 92,["Kills"] = 21},
    ["Stonesplinter Scout"] = {["Rank"] = 93,["Kills"] = 21},
    ["Gradok"] = {["Rank"] = 94,["Kills"] = 19},
    ["Xabraxxis"] = {["Rank"] = 95,["Kills"] = 19},
    ["Sri'skulk"] = {["Rank"] = 96,["Kills"] = 19},
    ["Goretusk"] = {["Rank"] = 97,["Kills"] = 19},
    ["Polly"] = {["Rank"] = 98,["Kills"] = 19},
    ["Defias Raider"] = {["Rank"] = 99,["Kills"] = 19},
    ["Murloc Netter"] = {["Rank"] = 100,["Kills"] = 19},

    -- Players
    ["Valkar"] = {["Rank"] = 1,["Kills"] = 123},
    ["Zdraxus"] = {["Rank"] = 2,["Kills"] = 11},
    ["Grimus"] = {["Rank"] = 3,["Kills"] = 9},
    ["Lilrat"] = {["Rank"] = 4,["Kills"] = 8},
    ["Dimkosyan"] = {["Rank"] = 5,["Kills"] = 8},
    ["Evolvz"] = {["Rank"] = 6,["Kills"] = 6},
    ["Greengnom"] = {["Rank"] = 7,["Kills"] = 6},
    ["Slimshadowy"] = {["Rank"] = 8,["Kills"] = 5},
    ["Bamboozler"] = {["Rank"] = 9,["Kills"] = 5},
    ["Jimmycarrey"] = {["Rank"] = 10,["Kills"] = 5},
    ["Gevilgaz"] = {["Rank"] = 11,["Kills"] = 4},
    ["Eemodru"] = {["Rank"] = 12,["Kills"] = 4},
    ["Glin"] = {["Rank"] = 13,["Kills"] = 4},
    ["Pekora"] = {["Rank"] = 14,["Kills"] = 4},
    ["Yourmotherr"] = {["Rank"] = 15,["Kills"] = 3},
    ["Zaradur"] = {["Rank"] = 16,["Kills"] = 3},
    ["Mossadagent"] = {["Rank"] = 17,["Kills"] = 3},
    ["Elkrinia"] = {["Rank"] = 18,["Kills"] = 3},
    ["Shacklez"] = {["Rank"] = 19,["Kills"] = 3},
    ["Proy"] = {["Rank"] = 20,["Kills"] = 3},
    ["Deaddy"] = {["Rank"] = 21,["Kills"] = 2},
    ["Sammara"] = {["Rank"] = 22,["Kills"] = 2},
    ["Nestro"] = {["Rank"] = 23,["Kills"] = 2},
    ["Gungner"] = {["Rank"] = 24,["Kills"] = 2},
    ["Ripbozohaha"] = {["Rank"] = 25,["Kills"] = 2},
    ["Chrisophia"] = {["Rank"] = 26,["Kills"] = 2},
    ["Bloats"] = {["Rank"] = 27,["Kills"] = 2},
    ["Olinson"] = {["Rank"] = 28,["Kills"] = 2},
    ["Greenpepe"] = {["Rank"] = 29,["Kills"] = 2},
    ["Shortstab"] = {["Rank"] = 30,["Kills"] = 2},
    ["Lichking"] = {["Rank"] = 31,["Kills"] = 2},
    ["Doob"] = {["Rank"] = 32,["Kills"] = 2},
    ["Akmetlt"] = {["Rank"] = 33,["Kills"] = 2},
    ["Chicagobulls"] = {["Rank"] = 34,["Kills"] = 2},
    ["Arkimonday"] = {["Rank"] = 35,["Kills"] = 2},
    ["Mangomazestv"] = {["Rank"] = 36,["Kills"] = 2},
    ["Forskintaker"] = {["Rank"] = 37,["Kills"] = 2},
    ["Jahh"] = {["Rank"] = 38,["Kills"] = 2},
    ["Turzog"] = {["Rank"] = 39,["Kills"] = 2},
    ["Med"] = {["Rank"] = 40,["Kills"] = 2},
    ["Petrichor"] = {["Rank"] = 41,["Kills"] = 2},
    ["Flardy"] = {["Rank"] = 42,["Kills"] = 1},
    ["Goodnews"] = {["Rank"] = 43,["Kills"] = 1},
    ["Maeryll"] = {["Rank"] = 44,["Kills"] = 1},
    ["Spacezm"] = {["Rank"] = 45,["Kills"] = 1},
    ["Haavoc"] = {["Rank"] = 46,["Kills"] = 1},
    ["Peacelocke"] = {["Rank"] = 47,["Kills"] = 1},
    ["Grimbatuul"] = {["Rank"] = 48,["Kills"] = 1},
    ["Minces"] = {["Rank"] = 49,["Kills"] = 1},
    ["Wrocko"] = {["Rank"] = 50,["Kills"] = 1},
    ["Megalomaniac"] = {["Rank"] = 51,["Kills"] = 1},
    ["Leprekon"] = {["Rank"] = 52,["Kills"] = 1},
    ["Smiles"] = {["Rank"] = 53,["Kills"] = 1},
    ["Nanachi"] = {["Rank"] = 54,["Kills"] = 1},
    ["Glitterati"] = {["Rank"] = 55,["Kills"] = 1},
    ["Lahvovic"] = {["Rank"] = 56,["Kills"] = 1},
    ["Rhazhai"] = {["Rank"] = 57,["Kills"] = 1},
    ["Funjke"] = {["Rank"] = 58,["Kills"] = 1},
    ["Alyara"] = {["Rank"] = 59,["Kills"] = 1},
    ["Fitslag"] = {["Rank"] = 60,["Kills"] = 1},
    ["Catfat"] = {["Rank"] = 61,["Kills"] = 1},
    ["Smoak"] = {["Rank"] = 62,["Kills"] = 1},
    ["Cato"] = {["Rank"] = 63,["Kills"] = 1},
    ["Terrorglaive"] = {["Rank"] = 64,["Kills"] = 1},
    ["Fante"] = {["Rank"] = 65,["Kills"] = 1},
    ["Deca"] = {["Rank"] = 66,["Kills"] = 1},
    ["Savitar"] = {["Rank"] = 67,["Kills"] = 1},
    ["Albertabeef"] = {["Rank"] = 68,["Kills"] = 1},
    ["Elwynboss"] = {["Rank"] = 69,["Kills"] = 1},
    ["Bedsteven"] = {["Rank"] = 70,["Kills"] = 1},
    ["Idk"] = {["Rank"] = 71,["Kills"] = 1},
    ["Dirby"] = {["Rank"] = 72,["Kills"] = 1},
    ["Zaas"] = {["Rank"] = 73,["Kills"] = 1},
    ["Grizzlie"] = {["Rank"] = 74,["Kills"] = 1},
    ["Lorivel"] = {["Rank"] = 75,["Kills"] = 1},
    ["Azzerz"] = {["Rank"] = 76,["Kills"] = 1},
    ["Kayaboume"] = {["Rank"] = 77,["Kills"] = 1},
    ["Wotanjugend"] = {["Rank"] = 78,["Kills"] = 1},
    ["Deadelivery"] = {["Rank"] = 79,["Kills"] = 1},
    ["Delerius"] = {["Rank"] = 80,["Kills"] = 1},
    ["Schneider"] = {["Rank"] = 81,["Kills"] = 1},
    ["Fallout"] = {["Rank"] = 82,["Kills"] = 1},
    ["Bootiebandit"] = {["Rank"] = 83,["Kills"] = 1},
    ["Faelwrynn"] = {["Rank"] = 84,["Kills"] = 1},
    ["Grovestalker"] = {["Rank"] = 85,["Kills"] = 1},
    ["Blackbiird"] = {["Rank"] = 86,["Kills"] = 1},
    ["Shiimanee"] = {["Rank"] = 87,["Kills"] = 1},
    ["Trentx"] = {["Rank"] = 88,["Kills"] = 1},
    ["Abwxo"] = {["Rank"] = 89,["Kills"] = 1},
    ["Tokyomane"] = {["Rank"] = 90,["Kills"] = 1},
    ["Dmn"] = {["Rank"] = 91,["Kills"] = 1},
    ["Effectivehc"] = {["Rank"] = 92,["Kills"] = 1},
    ["Bytheway"] = {["Rank"] = 93,["Kills"] = 1},
    ["Furryloverxo"] = {["Rank"] = 94,["Kills"] = 1},
    ["Landry"] = {["Rank"] = 95,["Kills"] = 1},
    ["Buranku"] = {["Rank"] = 96,["Kills"] = 1},
    ["Tuni"] = {["Rank"] = 97,["Kills"] = 1},
    ["Komowa"] = {["Rank"] = 98,["Kills"] = 1},
    ["Powerful"] = {["Rank"] = 99,["Kills"] = 1},
    ["Wickedjaw"] = {["Rank"] = 100,["Kills"] = 1},
}