MobWarn.mobs = {
    ["Defias Bodyguard"] = {["Rank"] = 1,["Kills"] = 198},
    ["Defias Highwayman"] = {["Rank"] = 2,["Kills"] = 146},
    ["Defias Trapper"] = {["Rank"] = 3,["Kills"] = 117},
    ["Rockjaw Bonesnapper"] = {["Rank"] = 4,["Kills"] = 96},
    ["Deepmoss Matriarch"] = {["Rank"] = 5,["Kills"] = 80},
    ["Tunnel Rat Geomancer"] = {["Rank"] = 6,["Kills"] = 74},
    ["Carver Molsen"] = {["Rank"] = 7,["Kills"] = 67},
    ["Vagash"] = {["Rank"] = 8,["Kills"] = 67},
    ["Unseen"] = {["Rank"] = 9,["Kills"] = 64},
    ["Rotting Ancestor"] = {["Rank"] = 10,["Kills"] = 59},
    ["Warlord Krom'zar"] = {["Rank"] = 11,["Kills"] = 59},
    ["Lunaclaw"] = {["Rank"] = 12,["Kills"] = 57},
    ["Voidwalker"] = {["Rank"] = 13,["Kills"] = 56},
    ["Bristleback Trapper"] = {["Rank"] = 14,["Kills"] = 54},
    ["Compact Harvest Reaper"] = {["Rank"] = 15,["Kills"] = 53},
    ["Sunscale Scytheclaw"] = {["Rank"] = 16,["Kills"] = 53},
    ["Burning Blade Apprentice"] = {["Rank"] = 17,["Kills"] = 50},
    ["Razormane Defender"] = {["Rank"] = 18,["Kills"] = 45},
    ["Son of Arugal"] = {["Rank"] = 19,["Kills"] = 44},
    ["Blackrock Outrunner"] = {["Rank"] = 20,["Kills"] = 44},
    ["Venture Co. Enforcer"] = {["Rank"] = 21,["Kills"] = 43},
    ["Riverpaw Outrunner"] = {["Rank"] = 22,["Kills"] = 43},
    ["Defias Pillager"] = {["Rank"] = 23,["Kills"] = 43},
    ["Defias Looter"] = {["Rank"] = 24,["Kills"] = 42},
    ["Fizzle Darkstorm"] = {["Rank"] = 25,["Kills"] = 41},
    ["Burning Blade Toxicologist"] = {["Rank"] = 26,["Kills"] = 41},
    ["Tunnel Rat Forager"] = {["Rank"] = 27,["Kills"] = 40},
    ["Murloc Tidehunter"] = {["Rank"] = 28,["Kills"] = 40},
    ["Benny Blaanco"] = {["Rank"] = 29,["Kills"] = 39},
    ["Tunnel Rat Kobold"] = {["Rank"] = 30,["Kills"] = 39},
    ["Wretched Bodyguard"] = {["Rank"] = 31,["Kills"] = 37},
    ["Stonesplinter Trogg"] = {["Rank"] = 32,["Kills"] = 37},
    ["Longsnout"] = {["Rank"] = 33,["Kills"] = 36},
    ["Stitches"] = {["Rank"] = 34,["Kills"] = 35},
    ["Riverpaw Bandit"] = {["Rank"] = 35,["Kills"] = 34},
    ["Ol' Sooty"] = {["Rank"] = 36,["Kills"] = 33},
    ["Dreadmaw Crocolisk"] = {["Rank"] = 37,["Kills"] = 33},
    ["Defias Pathstalker"] = {["Rank"] = 38,["Kills"] = 32},
    ["Harvest Watcher"] = {["Rank"] = 39,["Kills"] = 32},
    ["Stormscale Wave Rider"] = {["Rank"] = 40,["Kills"] = 32},
    ["Sand Shark"] = {["Rank"] = 41,["Kills"] = 31},
    ["Tunnel Rat Digger"] = {["Rank"] = 42,["Kills"] = 31},
    ["Murloc Coastrunner"] = {["Rank"] = 43,["Kills"] = 30},
    ["Defias Smuggler"] = {["Rank"] = 44,["Kills"] = 30},
    ["Carnivous the Breaker"] = {["Rank"] = 45,["Kills"] = 30},
    ["Imp Minion"] = {["Rank"] = 46,["Kills"] = 30},
    ["Razormane Stalker"] = {["Rank"] = 47,["Kills"] = 30},
    ["Kolkar Invader"] = {["Rank"] = 48,["Kills"] = 29},
    ["Hecklefang Hyena"] = {["Rank"] = 49,["Kills"] = 29},
    ["Theramore Marine"] = {["Rank"] = 50,["Kills"] = 28},
    ["Witchwing Slayer"] = {["Rank"] = 51,["Kills"] = 27},
    ["Lillith Nefara"] = {["Rank"] = 52,["Kills"] = 26},
    ["Defias Bandit"] = {["Rank"] = 53,["Kills"] = 26},
    ["Kolkar Packhound"] = {["Rank"] = 54,["Kills"] = 26},
    ["Foreman Grills"] = {["Rank"] = 55,["Kills"] = 25},
    ["Stonesplinter Skullthumper"] = {["Rank"] = 56,["Kills"] = 25},
    ["Raging Moonkin"] = {["Rank"] = 57,["Kills"] = 25},
    ["Southsea Cannoneer"] = {["Rank"] = 58,["Kills"] = 25},
    ["Kodo Matriarch"] = {["Rank"] = 59,["Kills"] = 25},
    ["Gnarlpine Shaman"] = {["Rank"] = 60,["Kills"] = 25},
    ["Ragefire Trogg"] = {["Rank"] = 61,["Kills"] = 25},
    ["Silithid Swarm"] = {["Rank"] = 62,["Kills"] = 24},
    ["Taskmaster Fizzule"] = {["Rank"] = 63,["Kills"] = 24},
    ["Rockjaw Skullthumper"] = {["Rank"] = 64,["Kills"] = 24},
    ["Greymist Coastrunner"] = {["Rank"] = 65,["Kills"] = 24},
    ["Moonstalker Runt"] = {["Rank"] = 66,["Kills"] = 24},
    ["Prowler"] = {["Rank"] = 67,["Kills"] = 24},
    ["Old Icebeard"] = {["Rank"] = 68,["Kills"] = 22},
    ["Riverpaw Brute"] = {["Rank"] = 69,["Kills"] = 22},
    ["Hogger"] = {["Rank"] = 70,["Kills"] = 22},
    ["Dire Condor"] = {["Rank"] = 71,["Kills"] = 22},
    ["Oggleflint"] = {["Rank"] = 72,["Kills"] = 22},
    ["Ornery Plainstrider"] = {["Rank"] = 73,["Kills"] = 21},
    ["Dragonmaw Raider"] = {["Rank"] = 74,["Kills"] = 21},
    ["Blackmoss the Fetid"] = {["Rank"] = 75,["Kills"] = 21},
    ["Bristleback Hunter"] = {["Rank"] = 76,["Kills"] = 21},
    ["Venture Co. Overseer"] = {["Rank"] = 77,["Kills"] = 21},
    ["Gnarlpine Augur"] = {["Rank"] = 78,["Kills"] = 20},
    ["Bristleback Thornweaver"] = {["Rank"] = 79,["Kills"] = 20},
    ["Burning Blade Fanatic"] = {["Rank"] = 80,["Kills"] = 20},
    ["Gnarlpine Defender"] = {["Rank"] = 81,["Kills"] = 20},
    ["Defias Knuckleduster"] = {["Rank"] = 82,["Kills"] = 19},
    ["Gradok"] = {["Rank"] = 83,["Kills"] = 19},
    ["Dalaran Serpent"] = {["Rank"] = 84,["Kills"] = 19},
    ["Verog the Dervish"] = {["Rank"] = 85,["Kills"] = 19},
    ["Razormane Water Seeker"] = {["Rank"] = 86,["Kills"] = 19},
    ["Galak Assassin"] = {["Rank"] = 87,["Kills"] = 18},
    ["Foe Reaper 4000"] = {["Rank"] = 88,["Kills"] = 17},
    ["Thistle Bear"] = {["Rank"] = 89,["Kills"] = 17},
    ["Stonesplinter Scout"] = {["Rank"] = 90,["Kills"] = 17},
    ["Murloc Oracle"] = {["Rank"] = 91,["Kills"] = 17},
    ["Defias Dockmaster"] = {["Rank"] = 92,["Kills"] = 16},
    ["Sri'skulk"] = {["Rank"] = 93,["Kills"] = 16},
    ["Venture Co. Drudger"] = {["Rank"] = 94,["Kills"] = 16},
    ["Deepmoss Creeper"] = {["Rank"] = 95,["Kills"] = 16},
    ["Gazz'uz"] = {["Rank"] = 96,["Kills"] = 16},
    ["Thragomm"] = {["Rank"] = 97,["Kills"] = 16},
    ["Devouring Ectoplasm"] = {["Rank"] = 98,["Kills"] = 16},
    ["Stonesplinter Seer"] = {["Rank"] = 99,["Kills"] = 16},
    ["Defias Raider"] = {["Rank"] = 100,["Kills"] = 16},
}